# Reference Page #####################################
## http://d.hatena.ne.jp/k2jp/20101108/1289197446
## http://d.hatena.ne.jp/k2jp/20081010/p1
## http://d.hatena.ne.jp/k2jp/20080916/p3

{-filter{pad_s}}
#####################################################
.go.jp/
dl.plustar.jp/
#as.dc.impact-ad.jp/
*.impact-ad.jp/
i-mdrive.co.jp/

# Adult ##############################################
video.fc2.com/a/
*.jp-sex.com/
*.megafilex.com/
.dmm.co.jp/
*.youjizz.com/
www.pornhost.com/
www.ppc-direct.com/
www.mmaaxx.com/
.dtiblog.com/
yvh.cc/
www.xvideos.com
xhamster.com/
*.dtiserv2.com/
*.dtiserv.com/
*.caribbeancom.com/
www.max-v.net/
www.megaporn.com/
www.xhamster.com/
*.tube8.com/
www.pornhost.com/
www.xvideos.com/
www.tokyo-porn-tube.com/
www.yourfilehost.com/
www.trovaporno.com/
www.nukistream.com/
nukistream.com/
*.exoclick.com/
www.espace-adulte.com/
www.sexandtrash.com/
*.dtiserv2.com/
aff-jp.dxlive.com/
*.mmaaxx.com/
mmaaxx.com/
*.kanjukulive.com/
*.caribbeancomgirl.com/
www.ppc-direct.com/
www.max-v.net/
www.pornhost.com/
hikaritube.com/
*.userporn.com/
www.megaporn.com/
*.dmm.com/
rannking.com/
*.omany.tv/
*.kadoebi.co.jp/

# video domain #######################################
player.vimeo.com/
.apserver.net/
yvhmovie.com/
ext.nicovideo.jp/

# amazon domain ######################################
rcm-jp.amazon.co.jp/
ws.amazon.co.jp/
wms.assoc-amazon.jp/
amazon.plustar.jp/

# blog parts #########################################
/blogparts/
/.*/blogparts/
/widget.*
/.*/widget.*
/gadget.*
/.*/gadget.*
/parts.*
/.*/parts.*
/blog_parts*
#http://h.hatena.ne.jp/k2jp/?height=300&mode=widget&width=220
h.hatena.ne.jp/*
h.hatena.ne.jp/widget*
www.google.com/talk/service/badge/Show*
b.hatena.ne.jp/entry/panel/*

# share button
share.gree.jp/
plugins.mixi.jp/
.twitter.com/widgets/
#http://www.facebook.com/plugins/fan.php
www.facebook.com/plugins/

# other ##############################################
/iframe/
/iframes/
/button/
/buttons/
/module/
/modules/
/menu.php
/menu.html*
#http://www.blogger.com/navbar.g?targetBlogID=4530875953866513005&blogName=Mashiki%27s+javascript+note&publishMode=PUBLISH_MODE_BLOGSPOT&navbarType=BLACK&layoutType=LAYOUTS&searchRoot=http%3A%2F%2Fmashiki-memo.blogspot.com%2Fsearch&blogLocale=ja&homepageUrl=http%3A%2F%2Fmashiki-memo.blogspot.com%2F
www.blogger.com/navbar.g
#<iframe scrolling="no" frameborder="0" style="width:110px; height:20px;" scrollbars="no" allowtransparency="true" role="presentation" src="//s7.addthis.com/static/r07/tweet04.html#href="></iframe>
*.addthis.com/
*.api.twitter.com/
*.daum.net/FrmRelated/*
/iframe.*
/.*/iframe.*
/teama.*
/jpn/emc.*

# media
/Media/dct-tv/

# rss 
/rss_bbs2/

/p/o/r/
/m/u/r/
/b/a/k/

# local ##############################################
192.*/
172.*/
10.*/

# ad Adult ###########################################
*.star-advertising.com/
s.xvideos.com/
live-add.com/
*.sbs-ad.com/
*.affiliate-dti.com/
#http://cdn.zeusclicks.com/ads/adult/iframes/190x900youjizz2.html
*.zeusclicks.com/
#http://loading321.com/delivery/ajs.php?zoneid=3&target=_blank&block=1&blockcampaign=1&cb=17201988804&charset=ISO-8859-1&loc=http%3A//s.xvideos.com/right-ad-white.php%3F
#<iframe width="338" scrolling="no" height="235" frameborder="0" src="http://adsformula.sitescout.com/cst/xvideos_ntv2.jsp" marginwidth="0" marginheight="0" hspace="0" vspace="0" bordercolor="#000000"></iframe>
*.sitescout.com/
#<script src="http://loading321.com/delivery/ajs.php?zoneid=3&amp;target=_blank&amp;block=1&amp;blockcampaign=1&amp;cb=79844854608&amp;charset=ISO-8859-1&amp;loc=http%3A//s.xvideos.com/right-ad-white.php%3F" type="text/javascript"></script>
#<iframe width="338" scrolling="no" height="235" frameborder="0" allowtransparency="true" marginheight="0" marginwidth="0" src="http://ads.fling.com/www/delivery/afr.php?zoneid=408"></iframe>
*.fling.com/
#<script src="http://loading321.com/delivery/ajs.php?zoneid=3&amp;target=_blank&amp;block=1&amp;blockcampaign=1&amp;cb=36028636165&amp;charset=ISO-8859-1&amp;loc=http%3A//s.xvideos.com/right-ad-white.php%3F" type="text/javascript"></script>
#<iframe width="338" scrolling="no" height="235" frameborder="0" src="http://www.pornografish.com/ox_zones/xvideos_cube.php"></iframe>
*.pornografish.com/

# netcafe #############################################
*.jword.jp/
#http://www.kingsoft.jp/office/tip.php?infotype=dailytip&app=wps&vernum=6.6.0.2505&vertype=professional&lan=1041&local=japan&featureltd=full&tipid=0.4785&guid=39F1AAE7-F351-4286-B0F7-002026077EDA&Auth=91CF0DE5996B4576583469D6A4B63BDD&pt=00009.00000001
*.kingsoft.jp/
*.w3support.net/
*.ptn.woopie.jp/
*.fooooo.com/

# OnlineGame #########################################
nexon.co.jp/
*.nexon.co.jp/
redsonline.jp/
*.redsonline.jp/
talesweaver.jp/
*.talesweaver.jp/
mabinogi.jp/
*.mabinogi.jp/
777town.net/
*.777town.net/
gamechu.jp/
*.gamechu.jp/
hangame.co.jp/
*.hangame.co.jp/
daletto.com/
*.daletto.com/
cronous.jp/
*.cronous.jp/
atgames.jp/
atgames.jp/
*.atgames.jp/
arad.jp/
*.arad.jp/
plaync.jp/
*.plaync.jp/
mh-frontier.jp/
*.mh-frontier.jp/
lineage2.jp/
*.lineage2.jp/
sengokuixa.jp/
*.sengokuixa.jp/
gungho.jp/
*.gungho.jp/
muonline.jp/
*.muonline.jp/
paynetcafe.com/
*.paynetcafe.com/
roseon.jp/
*.roseon.jp/
lineage.jp/
*.lineage.jp/
entercrews.com/
*.entercrews.com/
*.redsonline.jp/
games.yahoo.co.jp/
*.dofus.jp/
garema.jp/
*.garema.jp/
*.hanbitstation.jp/
pandorasaga.com/
*.pandorasaga.com/
oge.jp/
*.oge.jp/
mk-style.com/
*.mk-style.com/
rohan.jp/
*.rohan.jp/
ujj.co.jp/
*.ujj.co.jp/
ragnarokonline.jp/
*.ragnarokonline.jp/
arario.jp/
*.arario.jp/
moepic.com/
*.moepic.com/
druaga-mmo.com/
*.druaga-mmo.com/
game11.jp/
*.game11.jp/
sunonline.jp/
*.sunonline.jp/
gpotato.jp/
*.gpotato.jp/
musou-online.jp/
*.musou-online.jp/
arario.jp/
*.arario.jp/
avaonline.jp/
*.avaonline.jp/
gamecom.jp/
*.gamecom.jp/
mgame.jp/
*.mgame.jp/
gamers1.jp/
*.gamers1.jp/
gamescampus.co.jp/
*.gamescampus.co.jp/
pangya.jp/
*.pangya.jp/
yakyutsuku-online.com/
*.yakyutsuku-online.com/
joycity.jp/
*.joycity.jp/
eafifaonline.jp/
*.eafifaonline.jp/
ownersleague.jp/
*.ownersleague.jp/
webga.jp/
*.webga.jp/
bg-time.jp/
*.bg-time.jp/
3gokushi.jp/
*.3gokushi.jp/
gamecity.ne.jp/
*.gamecity.ne.jp/
aeriagames.jp/
*.aeriagames.jp/
gameleon.jp/
*.gameleon.jp/
sdgundamcfo.jp/
*.sdgundamcfo.jp/
bokumono.com/
*.bokumono.com/
gamecity.ne.jp/
*.gamecity.ne.jp/
*.weros.jp/
mebius-online.jp/
*.mebius-online.jp/
*.cabal.jp/
*.fezero.jp/
*.latale.jp/
*.paperman.jp/
*.postar.jp/
*.gamepot.co.jp/
*.maru-jan.com/
*.ron2.jp/
*.kinma.jp/
*.k-den.jp/
*.jan-revo.com/
tetsuya-tonpu.com/
*.pairon.jp/
*.casinogame.jp/
pupe.ameba.jp/
*.nicotto.jp/
*.gummy.jp/
*.ozworld.jp/
*.hs-online.jp/entrance/
gamespace24.net/
grandfantasia.jp/
*.trickster.jp/welcome/
*.gameyarou.jp/
*.bravesongonline.jp/
*.gno3.ne.jp/
*.suparobo.jp/
codemasters.jp/
*.megatenonline.com/
*.gamania.co.jp/
*.pspace.jp/
gree.jp/
*.gree.jp/
pso2.jp/
*.pso2.jp/
hoshi-umi.com/
*.hoshi-umi.com/
kbmj.com/
*.kbmj.com/
bandainamco-ol.jp/
*.bandainamco-ol.jp/
diablo3.com/
*.diablo3.com/
*.blizzard.com/
apps.facebook.com/
*.battle.net/
horiking.jp/
*.horiking.jp/
*.gameheart.jp/
*.dqx.jp/
dqx.jp/
*.ownershorse.jp/
ownershorse.jp/
*.wemade.com/
*.shikihime-fudasen.com/
*.ingame.jp/
*.thesecretworld.com/
aurcus.jp/
*.gameq.jp/
*.gsgame.jp/
*.koramgame.co.jp/
plaync.com/
*.plaync.com/
*.ss-alpha.net/
*.my-gg.com/
*.toywars.jp/
ingame.jp/
*.ingame.jp/
*.haoden.jp/

# ameba pigg
*.pigg.ameba.jp/
pigg-life.ameba.jp/
pigg.ameba.jp/

# netcafe Adult ######################################
ip1.dmm.co.jp/
*.v-ch.com/
sodbb.com/
*.sodbb.com/

# runsystem ##########################################
link.tenki-yoho.com/
*.runsystem.co.jp/
jiqoo.jp/
*.jiqoo.jp/
*.i-mobile.co.jp/

# geragera ###########################################
#http://netcafe.toolbar.jp/adtoolbar/geragera/tbinline/toolbar_page.php
netcafe.toolbar.jp/
#http://ss.adingo.jp.eimg.jp/cafe/toolbar/toolbar_body/common_html/?id=1
ss.adingo.jp.eimg.jp/
*.geragera.co.jp/
onsou.dice.co.jp/
geragera.shop-pro.jp/
www.prestige-cafe.net/

# system #############################################
*.windowsupdate.microsoft.com/
update.microsoft.com/
*.update.microsoft.com/
download.windowsupdate.com/
download.microsoft.com/
*.download.windowsupdate.com/
wustat.windows.com/
*.gowindowslive.com/
*.mcafeeasap.ne.jp/

# mail ###############################################
jp.*.mail.yahoo.co.jp/
*.*.mail.live.com/
mail.google.com/
mail.livedoor.com/

# tse corp ###########################################
*.jrc.co.jp/*
*.aa-material.co.jp/*
*.xebio.co.jp/*
*.fukuicompu.co.jp/*
weathernews.jp/*
wbt.valor.co.jp/*
tokai.jp/*
tigers.jp/*
suminoe.jp/*
smth.jp/*
sfc.jp/*
schd.toyoinkgroup.com/*
ryohin-keikaku.jp/*
right-on.co.jp/*
pioneer.jp/*
park24.co.jp/*
panasonic.co.jp/*
panasonic-denkois.co.jp/*
panasonic-denko.co.jp/*
nissin.jp/*
melco-hd.jp/*
konicaminolta.jp/*
kakaku.com/*
kabu.com/*
jp.yamatake.com/*
jp.trendmicro.com/*
jp.hamamatsu.com/*
jp.fujitsu.com/*
japan.renesas.com/*
housefoods.jp/*
holdings.hankyu-hanshin.co.jp/*
hitachi-business.com/*
dwango.jp/*
dccorp.jp/*
cybozu.co.jp/*
cyber.promise.co.jp/*
corporate.saisoncard.co.jp/*
corporate.m3.com/*
const.tokyu.com/*
company.gakujo.ne.jp/*
columbia.jp/*
cleanup.jp/*
cb-asahi.co.jp/*
canon.jp/*
asahi-net.jp/*
*.zuken.co.jp/*
*.zeria.co.jp/*
*.zeon.co.jp/*
*.zensho.co.jp/*
*.zenrin.co.jp/*
*.zappallas.com/*
*.zacros.co.jp/*
*.yushiro.co.jp/*
*.yushin.com/*
*.yusen.co.jp/*
*.yurtec.co.jp/*
*.yuki-gosei.co.jp/*
*.yuken.co.jp/*
*.yuden.co.jp/*
*.yuasa.co.jp/*
*.yskf.jp/*
*.yrc.co.jp/*
*.yoshinoya-holdings.com/*
*.yorozu-corp.co.jp/*
*.yonekyu.co.jp/*
*.yondenko.co.jp/*
*.yonden.co.jp/*
*.yomiuriland.co.jp/*
*.yomeishu.co.jp/*
*.yokowo.co.jp/*
*.yokorei.co.jp/*
*.yokogawa.co.jp/*
*.yodoko.co.jp/*
*.ymfg.co.jp/*
*.yellowhat.jp/*
*.ybhd.co.jp/*
*.yasuda-soko.co.jp/*
*.yaskawa.co.jp/*
*.yashimadenki.co.jp/*
*.yaoko-net.com/*
*.yamazen.co.jp/*
*.yamazawa.co.jp/*
*.yamazakipan.co.jp/*
*.yamaya.jp/*
*.yamaura.co.jp/*
*.yamatokogyo.co.jp/*
*.yamatointr.co.jp/*
*.yamato-se.co.jp/*
*.yamato-hd.co.jp/*
*.yamatane.co.jp/*
*.yamashitaika.co.jp/*
*.yamanashibank.co.jp/*
*.yamamura.co.jp/*
*.yamaichi.co.jp/*
*.yamaha.co.jp/*
*.yamaha-motor.co.jp/*
*.yamagatabank.co.jp/*
*.yamada-denki.jp/*
*.yamabiko-corp.co.jp/*
*.yakult.co.jp/*
*.yahagi.co.jp/*
*.yachiyobank.co.jp/*
*.yac.co.jp/*
*.xnet.co.jp/*
*.woodone.co.jp/*
*.westjr.co.jp/*
*.we-are-csp.co.jp/*
*.wave-nakano.co.jp/*
*.watami.co.jp/*
*.watabe-wedding.co.jp/*
*.warehouse.co.jp/*
*.warabeya.co.jp/*
*.wakamoto-pharm.co.jp/*
*.wakachiku.co.jp/*
*.wacom.co.jp/*
*.wacoalholdings.jp/*
*.vtec.co.jp/*
*.vitalksk.co.jp/*
*.vilene.co.jp/*
*.veriserve.co.jp/*
*.vantec-gl.com/*
*.valqua.co.jp/*
*.utoc.co.jp/*
*.ussnet.co.jp/*
*.ushio.co.jp/*
*.uny.co.jp/*
*.unitika.co.jp/*
*.united-arrows.co.jp/*
*.unisys.co.jp/*
*.unipres.co.jp/*
*.uniontool.co.jp/*
*.uniden.co.jp/*
*.unicharm.co.jp/*
*.unicafe.com/*
*.ulvac.co.jp/*
*.ukcgroup.com/*
*.uekigumi.co.jp/*
*.uchida.co.jp/*
*.ube-ind.co.jp/*
*.u-shin-ltd.com/*
*.tyk.co.jp/*
*.tv-asahi.co.jp/*
*.ttfuhan.co.jp/*
*.tte-net.co.jp/*
*.tt-paper.co.jp/*
*.tsutsumi.co.jp/*
*.tsurumipump.co.jp/*
*.tsuruha-hd.co.jp/*
*.tsumura.co.jp/*
*.tsukubabank.co.jp/*
*.tsukamoto.co.jp/*
*.tsugami.co.jp/*
*.tsudakoma.co.jp/*
*.tsubakimoto.jp/*
*.tsubaki.co.jp/*
*.tstech.co.jp/*
*.tsk-g.co.jp/*
*.tsi-holdings.com/*
*.tscom.co.jp/*
*.trusco.co.jp/*
*.trans-cosmos.co.jp/*
*.trancy.co.jp/*
*.trad.co.jp/*
*.tpr.co.jp/*
*.toyotanso.co.jp/*
*.toyota.co.jp/*
*.toyota-tsusho.com/*
*.toyota-shokki.co.jp/*
*.toyota-boshoku.co.jp/*
*.toyota-body.co.jp/*
*.toyosugar.co.jp/*
*.toyokohan.co.jp/*
*.toyokanetsu.co.jp/*
*.toyofuto.co.jp/*
*.toyodenki.co.jp/*
*.toyoda-gosei.co.jp/*
*.toyobo.co.jp/*
*.toyo.co.jp/*
*.toyo-shutter.co.jp/*
*.toyo-seikan.co.jp/*
*.toyo-sec.co.jp/*
*.toyo-rubber.co.jp/*
*.toyo-mm.co.jp/*
*.toyo-logistics.co.jp/*
*.toyo-eng.co.jp/*
*.toyo-const.co.jp/*
*.towayakuhin.jp/*
*.towajapan.co.jp/*
*.towabank.co.jp/*
*.tow.co.jp/*
*.toukei.co.jp/*
*.touei.co.jp/*
*.tottoribank.co.jp/*
*.totoku.co.jp/*
*.toto.co.jp/*
*.totetsu.co.jp/*
*.totenko.co.jp/*
*.tosoh.co.jp/*
*.tosho.co.jp/*
*.toshibatec.co.jp/*
*.toshiba.co.jp/*
*.toshiba-tpsc.co.jp/*
*.toshiba-machine.co.jp/*
*.tose.co.jp/*
*.torishima.co.jp/*
*.torii.co.jp/*
*.toray.co.jp/*
*.topy.co.jp/*
*.topre.co.jp/*
*.toppan.co.jp/*
*.toppan-f.co.jp/*
*.topculture.co.jp/*
*.topcon.co.jp/*
*.tonengeneral.co.jp/*
*.tonami.co.jp/*
*.tomony-hd.co.jp/*
*.tomoku.co.jp/*
*.tomoegawa.co.jp/*
*.tomoe-corporation.co.jp/*
*.tomo-e.co.jp/*
*.tominbank.co.jp/*
*.tomendevices.co.jp/*
*.tomen-ele.co.jp/*
*.tomatobank.co.jp/*
*.tomas.co.jp/*
*.toli.co.jp/*
*.tokyu.co.jp/*
*.tokyu-land.co.jp/*
*.tokyu-com.co.jp/*
*.tokyotokeiba.co.jp/*
*.tokyotekko.co.jp/*
*.tokyosteel.co.jp/*
*.tokyorope.co.jp/*
*.tokyo-gas.co.jp/*
*.tokyo-dome.co.jp/*
*.tokyo-airport-bldg.co.jp/*
*.tokuyama.co.jp/*
*.tokodenki.co.jp/*
*.toko.co.jp/*
*.tokiomarinehd.com/*
*.tokimec.co.jp/*
*.token.co.jp/*
*.tokaitokyo-fh.jp/*
*.tokaikanko.co.jp/*
*.tokaicarbon.co.jp/*
*.tokai.co.jp/*
*.tokai-senko.co.jp/*
*.tokai-rika.co.jp/*
*.tok.co.jp/*
*.tohsui.co.jp/*
*.tohpe.co.jp/*
*.tohoku-epco.co.jp/*
*.tohoku-bank.co.jp/*
*.tohohd.co.jp/*
*.tohogas.co.jp/*
*.tohobank.co.jp/*
*.toho.co.jp/*
*.toho-zinc.co.jp/*
*.toho-titanium.co.jp/*
*.toho-re.co.jp/*
*.toenec.co.jp/*
*.toei.co.jp/*
*.todakogyo.co.jp/*
*.toda.co.jp/*
*.tochigibank.co.jp/*
*.tocalo.co.jp/*
*.toc.co.jp/*
*.tobustore.co.jp/*
*.tobu.co.jp/*
*.tobishima.co.jp/*
*.toagosei.co.jp/*
*.toadoro.co.jp/*
*.toabo.co.jp/*
*.toa.co.jp/*
*.toa-const.co.jp/*
*.to-ho.co.jp/*
*.tn-sanso.co.jp/*
*.tks-net.co.jp/*
*.tkc.co.jp/*
*.titankogyo.co.jp/*
*.thk.com/*
*.thepack.co.jp/*
*.theatres.co.jp/*
*.the-torigoe.co.jp/*
*.the-fuji.com/*
*.tgn.co.jp/*
*.tew.co.jp/*
*.terumo.co.jp/*
*.tepco.co.jp/*
*.tenmacorp.co.jp/*
*.teng.co.jp/*
*.temp-holdings.co.jp/*
*.tel.com/*
*.tekken.co.jp/*
*.teisen.co.jp/*
*.teikokudenki.co.jp/*
*.teijin.co.jp/*
*.technomedica.co.jp/*
*.tech.softbank.co.jp/*
*.teac.co.jp/*
*.tdk.co.jp/*
*.tdc.co.jp/*
*.td-holdings.co.jp/*
*.tbsholdings.co.jp/*
*.tbk-jp.com/*
*.tayca.co.jp/*
*.taya.co.jp/*
*.taxan.co.jp/*
*.tatsuta.co.jp/*
*.tatemono.com/*
*.tasaki.co.jp/*
*.tanseisha.co.jp/*
*.tanakashoji.co.jp/*
*.tamura-ss.co.jp/*
*.tamron.co.jp/*
*.takuma.co.jp/*
*.takizawaham.co.jp/*
*.takiron.co.jp/*
*.takihyo.co.jp/*
*.takeda.co.jp/*
*.takata.com/*
*.takashimaya.co.jp/*
*.takasago-i.co.jp/*
*.takaratomy.co.jp/*
*.takara.co.jp/*
*.takara-standard.co.jp/*
*.takara-print.co.jp/*
*.takaoka.co.jp/*
*.takano-net.co.jp/*
*.takamatsu-const.co.jp/*
*.takadakiko.com/*
*.takachiho-kk.co.jp/*
*.taka-q.com/*
*.tak.co.jp/*
*.taiyo-hd.co.jp/*
*.taisho-holdings.co.jp/*
*.taiseirotec.co.jp/*
*.taisei.co.jp/*
*.taikobank.jp/*
*.taikisha.co.jp/*
*.taihonet.co.jp/*
*.taiheiyo.net/*
*.taiheiyo-cement.co.jp/*
*.taiheikogyo.co.jp/*
*.taihei-dengyo.co.jp/*
*.tadano.co.jp/*
*.tacthome.co.jp/*
*.tachibana.co.jp/*
*.tachi-s.co.jp/*
*.tac-school.co.jp/*
*.t-hasegawa.co.jp/*
*.t-gaia.co.jp/*
*.systena.co.jp/*
*.sysmex.co.jp/*
*.sxl.co.jp/*
*.swcc.co.jp/*
*.suzutan.co.jp/*
*.suzuki.co.jp/*
*.suzuken.co.jp/*
*.suzuden.co.jp/*
*.suteki-nice.jp/*
*.surugabank.co.jp/*
*.sunwa.co.jp/*
*.sunfrt.co.jp/*
*.sundrug.co.jp/*
*.sumitomoseika.co.jp/*
*.sumitomometals.co.jp/*
*.sumitomokokan.co.jp/*
*.sumitomocorp.co.jp/*
*.sumitomo-soko.co.jp/*
*.sumitomo-rd.co.jp/*
*.sumitomo-lm.co.jp/*
*.sumitomo-chem.co.jp/*
*.sumiseki.co.jp/*
*.sumikinbussan.co.jp/*
*.sumida.com/*
*.sumibe.co.jp/*
*.sumcosi.com/*
*.sugi-net.co.jp/*
*.subaru-kougyou.jp/*
*.studio-alice.co.jp/*
*.sthdg.co.jp/*
*.stepon.co.jp/*
*.stella-chemifa.co.jp/*
*.starzen.co.jp/*
*.star-m.jp/*
*.stanley.co.jp/*
*.st-c.co.jp/*
*.ssk-sasebo.co.jp/*
*.srt.co.jp/*
*.srigroup.co.jp/*
*.sri-sports.co.jp/*
*.sra-hd.co.jp/*
*.square-enix.com/*
*.spp.co.jp/*
*.spk.co.jp/*
*.sourcenext.com/*
*.sotetsu.co.jp/*
*.soshin.co.jp/*
*.sonyfh.co.jp/*
*.sony.co.jp/*
*.sojitz.com/*
*.sogo-medical.co.jp/*
*.softcreate.co.jp/*
*.softbank.co.jp/*
*.sodanikka.co.jp/*
*.soc.co.jp/*
*.so-net.ne.jp/*
*.snt.co.jp/*
*.snk.co.jp/*
*.snbl.co.jp/*
*.smm.co.jp/*
*.smk.co.jp/*
*.smfg.co.jp/*
*.smcworld.com/*
*.smcon.co.jp/*
*.skyperfectjsat.co.jp/*
*.sk-japan.co.jp/*
*.sinto.co.jp/*
*.sinfo-t.jp/*
*.sinanen.com/*
*.simplex-hd.co.jp/*
*.siix.co.jp/*
*.signal.co.jp/*
*.shuei-yobiko.co.jp/*
*.showa1.com/*
*.showa-shell.co.jp/*
*.showa-sangyo.co.jp/*
*.shokubai.co.jp/*
*.shoko.co.jp/*
*.shoei.co.jp/*
*.shochiku.co.jp/*
*.sho-bondhd.jp/*
*.shizuokagas.co.jp/*
*.shizuokabank.co.jp/*
*.shiseido.co.jp/*
*.shiroki.co.jp/*
*.shionogi.co.jp/*
*.shinyei.co.jp/*
*.shinwaship.co.jp/*
*.shinwa-jpn.co.jp/*
*.shinsho.co.jp/*
*.shinseibank.com/*
*.shinpoly.co.jp/*
*.shinnihon-c.co.jp/*
*.shinmaywa.co.jp/*
*.shinkobe-denki.co.jp/*
*.shinko.co.jp/*
*.shinko-sj.co.jp/*
*.shinkeisei.co.jp/*
*.shinkawa.com/*
*.shingakukai.co.jp/*
*.shinetsu.co.jp/*
*.shindengen.co.jp/*
*.shinagawa.co.jp/*
*.shimz.co.jp/*
*.shimojima.co.jp/*
*.shimizubank.co.jp/*
*.shimaseiki.co.jp/*
*.shimano.com/*
*.shimamura.gr.jp/*
*.shimadzu.co.jp/*
*.shimachu.co.jp/*
*.shikokubank.co.jp/*
*.shikoku.co.jp/*
*.shikibo.co.jp/*
*.shigagin.com/*
*.shibuya.co.jp/*
*.shibusawa.co.jp/*
*.shibaura.co.jp/*
*.shi.co.jp/*
*.sharp.co.jp/*
*.sgm.co.jp/*
*.sfoods.co.jp/*
*.senshukai.co.jp/*
*.senshuikeda-hd.co.jp/*
*.senko.co.jp/*
*.sem.co.jp/*
*.sekisuiplastics.co.jp/*
*.sekisuijushi.co.jp/*
*.sekisuihouse.co.jp/*
*.sekisui.co.jp/*
*.seirogan.co.jp/*
*.seiren.com/*
*.seino.co.jp/*
*.seiko.co.jp/*
*.seikitokyu.co.jp/*
*.seikagaku.co.jp/*
*.seika.com/*
*.seibu-denki.co.jp/*
*.sei.co.jp/*
*.segasammy.co.jp/*
*.secom.co.jp/*
*.sdk.co.jp/*
*.scsk.jp/*
*.scroll-shop.com/*
*.screen.co.jp/*
*.sbigroup.co.jp/*
*.saxa.co.jp/*
*.sawai.co.jp/*
*.sawafuji.co.jp/*
*.satoshoji.co.jp/*
*.satori.co.jp/*
*.sato.co.jp/*
*.satakensetsu.co.jp/*
*.sapporoholdings.jp/*
*.sapporohokuyo.co.jp/*
*.sanyo-steel.co.jp/*
*.sanyo-shokai.co.jp/*
*.sanyo-industries.co.jp/*
*.sanyo-hn.co.jp/*
*.sanyo-chemical.co.jp/*
*.sanwa-hldgs.co.jp/*
*.santen.co.jp/*
*.sansui-jpn.co.jp/*
*.sanshin.co.jp/*
*.sanrio.co.jp/*
*.sanoh.com/*
*.sankyu.co.jp/*
*.sankyoseiko.co.jp/*
*.sankyo-fever.co.jp/*
*.sankometal.co.jp/*
*.sanki.co.jp/*
*.sanken-ele.co.jp/*
*.sankeibldg.co.jp/*
*.sanix.co.jp/*
*.sangetsu.co.jp/*
*.sanden.co.jp/*
*.san-hd.co.jp/*
*.san-ai-oil.co.jp/*
*.san-a.co.jp/*
*.sala.jp/*
*.sakurada.co.jp/*
*.sakataseed.co.jp/*
*.sakaiovex.co.jp/*
*.sakainet.co.jp/*
*.sakai-chem.co.jp/*
*.saizeriya.co.jp/*
*.saint-marc-hd.com/*
*.saibugas.co.jp/*
*.sagami.co.jp/*
*.sagabank.co.jp/*
*.s-science.jp/*
*.s-re.jp/*
*.s-plantech.co.jp/*
*.ryugin.co.jp/*
*.ryoyo.co.jp/*
*.ryosan.co.jp/*
*.ryoden.co.jp/*
*.ryobi-group.co.jp/*
*.royal-holdings.co.jp/*
*.round1.co.jp/*
*.rolanddg.co.jp/*
*.roland.co.jp/*
*.rohto.co.jp/*
*.rohm.co.jp/*
*.rockfield.co.jp/*
*.riso.co.jp/*
*.rinnai.co.jp/*
*.ringerhut.co.jp/*
*.rikudenko.co.jp/*
*.rikuden.co.jp/*
*.rikentechnos.co.jp/*
*.rikenkeiki.co.jp/*
*.riken.co.jp/*
*.ricoh.co.jp/*
*.rhythm.co.jp/*
*.rheon.com/*
*.resorttrust.co.jp/*
*.resona-gr.co.jp/*
*.resol.jp/*
*.renown.com/*
*.rengo.co.jp/*
*.rasaco.co.jp/*
*.rasa.co.jp/*
*.rakutenchi.co.jp/*
*.raito.co.jp/*
*.r-lease.co.jp/*
*.qtes.co.jp/*
*.qso.co.jp/*
*.psmic.co.jp/*
*.pronexus.co.jp/*
*.primaham.co.jp/*
*.presskogyo.co.jp/*
*.poplar-cvs.co.jp/*
*.point.co.jp/*
*.pocketcard.co.jp/*
*.po-holdings.co.jp/*
*.plenus.co.jp/*
*.pixela.co.jp/*
*.piolax.co.jp/*
*.pilot.co.jp/*
*.pillar.co.jp/*
*.pigeon.co.jp/*
*.pia.co.jp/*
*.penta-ocean.co.jp/*
*.pegasus.co.jp/*
*.pasonagroup.co.jp/*
*.pasco.co.jp/*
*.parker.co.jp/*
*.paris-miki.com/*
*.parco.co.jp/*
*.paramountbed-hd.co.jp/*
*.panahome.jp/*
*.paltac.co.jp/*
*.palgroup.co.jp/*
*.pacificgolf.co.jp/*
*.pacific-metals.co.jp/*
*.pacific-ind.co.jp/*
*.oyo.co.jp/*
*.otsuka.com/*
*.otsuka-shokai.co.jp/*
*.osg.co.jp/*
*.osf.co.jp/*
*.osaki.co.jp/*
*.osakagas.co.jp/*
*.osaka-ti.co.jp/*
*.osaka-seitetu.co.jp/*
*.orix.co.jp/*
*.origin.co.jp/*
*.orico.co.jp/*
*.organo.co.jp/*
*.oracle.co.jp/*
*.optex.co.jp/*
*.onward.co.jp/*
*.onosokki.co.jp/*
*.onoken.co.jp/*
*.ono.co.jp/*
*.omron.co.jp/*
*.olympus.co.jp/*
*.olympic-corp.co.jp/*
*.olc.co.jp/*
*.okuwa.net/*
*.okumuragumi.co.jp/*
*.okuma.co.jp/*
*.okr-ind.co.jp/*
*.okk.co.jp/*
*.okinawa-bank.co.jp/*
*.okidensen.co.jp/*
*.okiden.co.jp/*
*.oki.com/*
*.okb.co.jp/*
*.okayaelec.co.jp/*
*.okasan.jp/*
*.okamura.co.jp/*
*.okamoto-inc.jp/*
*.okabe.co.jp/*
*.ojipaper.co.jp/*
*.oizumi.co.jp/*
*.oitabank.co.jp/*
*.oiles.co.jp/*
*.oie.co.jp/*
*.ohashi.co.jp/*
*.ohara-inc.co.jp/*
*.oenon.jp/*
*.odakyu.jp/*
*.obic.co.jp/*
*.obc.co.jp/*
*.obayashi.co.jp/*
*.obayashi-road.co.jp/*
*.obara-g.com/*
*.nyk.com/*
*.nyk.co.jp/*
*.nyc.co.jp/*
*.ntv.co.jp/*
*.nttud.co.jp/*
*.nttoryo.co.jp/*
*.nttdocomo.co.jp/*
*.nttdata.co.jp/*
*.ntt.co.jp/*
*.ntn.co.jp/*
*.nsw.co.jp/*
*.nsg.co.jp/*
*.nsd.co.jp/*
*.nsc.co.jp/*
*.ns-sol.co.jp/*
*.ns-net.co.jp/*
*.nri.co.jp/*
*.npr.co.jp/*
*.np-g.com/*
*.noritz.co.jp/*
*.noritsu.co.jp/*
*.noritake.co.jp/*
*.nomurakougei.co.jp/*
*.nomura.com/*
*.nomura-re-hd.co.jp/*
*.nok.co.jp/*
*.nohmi.co.jp/*
*.nof.co.jp/*
*.noble-j.co.jp/*
*.nksj-hd.com/*
*.nkchemical.co.jp/*
*.nkanzai.co.jp/*
*.njr.co.jp/*
*.nittsu.co.jp/*
*.nittoseimo.co.jp/*
*.nittoseiko.co.jp/*
*.nittofuji.co.jp/*
*.nittoc.co.jp/*
*.nittobo.co.jp/*
*.nitto.co.jp/*
*.nitto-kohki.co.jp/*
*.nittetsukou.co.jp/*
*.nitten.co.jp/*
*.nitta.co.jp/*
*.nitori.co.jp/*
*.nito.co.jp/*
*.nissui.co.jp/*
*.nissui-pharm.co.jp/*
*.nissinkogyo.co.jp/*
*.nissinfoods-holdings.co.jp/*
*.nissin-tw.co.jp/*
*.nissin-sugar-hldgs.co.jp/*
*.nisshinfudosan.co.jp/*
*.nisshinbo.co.jp/*
*.nisshin.com/*
*.nisshin-steel.co.jp/*
*.nisshin-oillio.com/*
*.nissha.co.jp/*
*.nissen.info/*
*.nisseijushi.co.jp/*
*.nisseibuild.co.jp/*
*.nissanchem.co.jp/*
*.nissan.co.jp/*
*.nissan-tokyo-hd.co.jp/*
*.nissan-shatai.co.jp/*
*.nishitetsu.co.jp/*
*.nishimatsu.co.jp/*
*.nisgroup.jp/*
*.nipro.co.jp/*
*.nipponseika.co.jp/*
*.nipponroad.co.jp/*
*.nipponpaint.co.jp/*
*.nipponkinzoku.co.jp/*
*.nipponkayaku.co.jp/*
*.nipponhume.co.jp/*
*.nipponham.co.jp/*
*.nippondenko.co.jp/*
*.nippon-soda.co.jp/*
*.nippon-shinyaku.co.jp/*
*.nippon-chem.co.jp/*
*.nippo-c.co.jp/*
*.nippn.co.jp/*
*.nippai.co.jp/*
*.nintendo.co.jp/*
*.nikon.co.jp/*
*.nikku.co.jp/*
*.nikkon.co.jp/*
*.nikko-net.co.jp/*
*.nikkiso.co.jp/*
*.nikkinko.co.jp/*
*.nikkeikin.co.jp/*
*.nikke.co.jp/*
*.nikkato.co.jp/*
*.nihonkohden.co.jp/*
*.nihon-trim.co.jp/*
*.nihon-ma.co.jp/*
*.nihon-kyoryo.co.jp/*
*.nifco.co.jp/*
*.nidec.co.jp/*
*.nidec-tosok.co.jp/*
*.nidec-sankyo.co.jp/*
*.nidec-copal.co.jp/*
*.nidec-copal-electronics.com/*
*.nichu.co.jp/*
*.nicho.co.jp/*
*.nichiyunet.co.jp/*
*.nichireki.co.jp/*
*.nichirei.co.jp/*
*.nichino.co.jp/*
*.nichimo.co.jp/*
*.nichiigakkan.co.jp/*
*.nichigo.co.jp/*
*.nichigas.co.jp/*
*.nichiden.com/*
*.nichicon.co.jp/*
*.nichiban.co.jp/*
*.nichiasteel.co.jp/*
*.nichias.co.jp/*
*.nicera.co.jp/*
*.nhkspg.co.jp/*
*.ngkntk.co.jp/*
*.ngk.co.jp/*
*.nexyz.co.jp/*
*.next-group.jp/*
*.netone.co.jp/*
*.netjpc.com/*
*.nesic.co.jp/*
*.neg.co.jp/*
*.necap.co.jp/*
*.nec.co.jp/*
*.nec-mobiling.com/*
*.nds-g.co.jp/*
*.ndk.com/*
*.ncic.co.jp/*
*.ncbank.co.jp/*
*.natori.co.jp/*
*.nantobank.co.jp/*
*.nankai.co.jp/*
*.nakayamafuku.co.jp/*
*.nakayama-steel.co.jp/*
*.nakamuraya.co.jp/*
*.nakabayashi.co.jp/*
*.naigai.co.jp/*
*.nagatanien.co.jp/*
*.nagase.co.jp/*
*.naganokeiki.co.jp/*
*.naganobank.co.jp/*
*.nagaileben.co.jp/*
*.nacoo.com/*
*.nachi-fujikoshi.co.jp/*
*.nabtesco.com/*
*.n-sharyo.co.jp/*
*.n-seisen.co.jp/*
*.n-p-d.co.jp/*
*.n-koei.co.jp/*
*.n-coke.com/*
*.mutoh-hd.co.jp/*
*.musashinobank.co.jp/*
*.musashi.co.jp/*
*.murata.co.jp/*
*.mufg.jp/*
*.mt-pharma.co.jp/*
*.msnw.co.jp/*
*.ms-ad-hd.com/*
*.mrmax.co.jp/*
*.mri.co.jp/*
*.mpuni.co.jp/*
*.mpm.co.jp/*
*.moshimoshi.co.jp/*
*.mos.co.jp/*
*.mory.co.jp/*
*.morozoff.co.jp/*
*.moritex.co.jp/*
*.morita119.com/*
*.moriseiki.co.jp/*
*.morinagamilk.co.jp/*
*.morinaga.co.jp/*
*.moresco.co.jp/*
*.monexbeans.net/*
*.mol.co.jp/*
*.modec.com/*
*.mochida.co.jp/*
*.mmc.co.jp/*
*.mizuno.co.jp/*
*.mizuho-fg.co.jp/*
*.miyoshi-yushi.co.jp/*
*.miyakoshi-holdings.com/*
*.miyaji-eng.com/*
*.miyagin.co.jp/*
*.miyachi.com/*
*.miuraz.co.jp/*
*.mitsuuroko.co.jp/*
*.mitsumura.co.jp/*
*.mitsumi.co.jp/*
*.mitsuihome.co.jp/*
*.mitsuifudosan.co.jp/*
*.mitsui.co.jp/*
*.mitsui-sugar.co.jp/*
*.mitsui-soko.co.jp/*
*.mitsui-matsushima.co.jp/*
*.mitsui-kinzoku.co.jp/*
*.mitsui-high-tec.com/*
*.mitsui-chem.co.jp/*
*.mitsuboshi.co.jp/*
*.mitsubishisteel.co.jp/*
*.mitsubishielectric.co.jp/*
*.mitsubishicorp.com/*
*.mitsubishichem-hd.co.jp/*
*.mitsubishi-shokuhin.com/*
*.mitsubishi-motors.co.jp/*
*.mitsubishi-logistics.co.jp/*
*.mitsuba.co.jp/*
*.mito.co.jp/*
*.mitachi.co.jp/*
*.misumi.co.jp/*
*.misawa.co.jp/*
*.mirait.co.jp/*
*.miraca-holdings.co.jp/*
*.ministop.co.jp/*
*.minebea.co.jp/*
*.minatobk.co.jp/*
*.mimasu.co.jp/*
*.milbon.co.jp/*
*.mikuni-ccbc.co.jp/*
*.miebank.co.jp/*
*.michinokubank.co.jp/*
*.mhi.co.jp/*
*.mgc.co.jp/*
*.mes.co.jp/*
*.meiwajisyo.co.jp/*
*.meiwa.co.jp/*
*.meiun.co.jp/*
*.meitetsu.co.jp/*
*.meitec.co.jp/*
*.meikonet.co.jp/*
*.meiji-shipping.com/*
*.meigin.com/*
*.meidensha.co.jp/*
*.megmilk-snowbrand.co.jp/*
*.meganetop.co.jp/*
*.megachips.co.jp/*
*.mediceo-paltac.co.jp/*
*.mec.co.jp/*
*.mec-co.com/*
*.mcml-maruken.com/*
*.mazda.co.jp/*
*.max-ltd.co.jp/*
*.matsuyafoods.co.jp/*
*.matsuya.com/*
*.matsumotokiyoshi-hd.co.jp/*
*.matsui.co.jp/*
*.matsui-ken.co.jp/*
*.matsuda-sangyo.co.jp/*
*.maspro.co.jp/*
*.maruzenshowa.co.jp/*
*.maruyama.co.jp/*
*.maruwn.co.jp/*
*.maruwa-g.com/*
*.marusan-sec.co.jp/*
*.maruka.co.jp/*
*.maruichikokan.co.jp/*
*.maruha-nichiro.co.jp/*
*.maruetsu.co.jp/*
*.maruei.ne.jp/*
*.marudai.jp/*
*.maruchan.co.jp/*
*.marubun.co.jp/*
*.marubeni.co.jp/*
*.mars-eng.co.jp/*
*.marche.co.jp/*
*.mapple.co.jp/*
*.mandom.co.jp/*
*.makita.co.jp/*
*.makino.co.jp/*
*.maezawa.co.jp/*
*.maezawa-k.co.jp/*
*.maedaroad.co.jp/*
*.maeda.co.jp/*
*.macromill.com/*
*.macnica.co.jp/*
*.mabuchi-motor.co.jp/*
*.look-inc.jp/*
*.livable.co.jp/*
*.lion.co.jp/*
*.lintec.co.jp/*
*.lifecorp.jp/*
*.lf.mufg.jp/*
*.leopalace21.co.jp/*
*.lecinc.co.jp/*
*.leben.co.jp/*
*.lbca.co.jp/*
*.lawson.co.jp/*
*.land.jp/*
*.lamick.co.jp/*
*.kyudenko.co.jp/*
*.kyuden.co.jp/*
*.kyowale.co.jp/*
*.kyowa-kirin.co.jp/*
*.kyowa-ei.co.jp/*
*.kyotokimonoyuzen.co.jp/*
*.kyotobank.co.jp/*
*.kyosan.co.jp/*
*.kyoritsugroup.co.jp/*
*.kyoritsu-printing.co.jp/*
*.kyorin-gr.co.jp/*
*.kyokuyo.co.jp/*
*.kyokuto.com/*
*.kyokuto-sec.co.jp/*
*.kyoeitanker.co.jp/*
*.kyoeisteel.co.jp/*
*.kyoei.co.jp/*
*.kyodoprinting.co.jp/*
*.kyodo-shiryo.co.jp/*
*.kyocera.co.jp/*
*.kyfg.com/*
*.kyb.co.jp/*
*.kwe.co.jp/*
*.kusuri-aoki.co.jp/*
*.kuroda-electric.co.jp/*
*.kurita.co.jp/*
*.kurimoto.co.jp/*
*.kureha.co.jp/*
*.kuraudia.co.jp/*
*.kuraray.co.jp/*
*.kurabo.co.jp/*
*.kura-corpo.co.jp/*
*.kumiai-chem.co.jp/*
*.kumagaigumi.co.jp/*
*.kubotek.com/*
*.kubota.co.jp/*
*.ksdenki.com/*
*.krs.co.jp/*
*.krosaki.co.jp/*
*.kourakuen.co.jp/*
*.koshuha.co.jp/*
*.kosei.co.jp/*
*.kose.co.jp/*
*.kosaido.co.jp/*
*.konami.co.jp/*
*.konaka.co.jp/*
*.komori.co.jp/*
*.komeri.bit.or.jp/*
*.komatsuwall.co.jp/*
*.komatsuseiren.co.jp/*
*.komatsu.co.jp/*
*.komaihaltec.co.jp/*
*.kokuyo.co.jp/*
*.kojima.net/*
*.koito.co.jp/*
*.kohsoku.com/*
*.koeitecmo.co.jp/*
*.kobetsu.co.jp/*
*.kobelco.co.jp/*
*.kobayashiyoko.com/*
*.kobayashi.co.jp/*
*.koatsugas.co.jp/*
*.koanet.co.jp/*
*.knt.co.jp/*
*.knn.co.jp/*
*.kline.co.jp/*
*.kkc-hd.co.jp/*
*.kk-alpha.com/*
*.kiw.co.jp/*
*.kitz.co.jp/*
*.kito.co.jp/*
*.kitazawasangyo.co.jp/*
*.kitano.co.jp/*
*.kitagin.co.jp/*
*.kissei.co.jp/*
*.kisoji.co.jp/*
*.kishu.co.jp/*
*.kirinholdings.co.jp/*
*.kirindo.co.jp/*
*.kinugawa-rubber.co.jp/*
*.kintetsu.jp/*
*.kinkisharyo.co.jp/*
*.kingjim.co.jp/*
*.kinden.co.jp/*
*.kimura-unity.co.jp/*
*.kimoto.co.jp/*
*.kikkoman.co.jp/*
*.khi.co.jp/*
*.keyence.co.jp/*
*.keycoffee.co.jp/*
*.kewpie.co.jp/*
*.kepco.co.jp/*
*.kentaku.co.jp/*
*.kenedix.com/*
*.kel.co.jp/*
*.keiyobank.co.jp/*
*.keiyo.co.jp/*
*.keisei.co.jp/*
*.keio.co.jp/*
*.keikyu.co.jp/*
*.keihin.co.jp/*
*.keihin-corp.co.jp/*
*.keihanshin.co.jp/*
*.keihan.co.jp/*
*.kddi.com/*
*.kcpc.co.jp/*
*.kbk.co.jp/*
*.kawai.co.jp/*
*.kawada.jp/*
*.katosangyo.co.jp/*
*.kato-works.co.jp/*
*.katakura.co.jp/*
*.kasumi.co.jp/*
*.kasai.co.jp/*
*.kappa-create.co.jp/*
*.kao.co.jp/*
*.kantodenka.co.jp/*
*.kanto-aw.co.jp/*
*.kansaiurban.co.jp/*
*.kansai.co.jp/*
*.kanematsu.co.jp/*
*.kaneka.co.jp/*
*.kandenko.co.jp/*
*.kanamoto.co.jp/*
*.kanaden.co.jp/*
*.kanachu.co.jp/*
*.kamipa.co.jp/*
*.kamigumi.co.jp/*
*.kamei.co.jp/*
*.kakoki.co.jp/*
*.kaken.co.jp/*
*.kajima.co.jp/*
*.kagome.co.jp/*
*.kagin.co.jp/*
*.kadokawa-hd.co.jp/*
*.k-neturen.co.jp/*
*.jvckenwood.co.jp/*
*.juroku.co.jp/*
*.juki.co.jp/*
*.jti.co.jp/*
*.jtekt.co.jp/*
*.jsw.co.jp/*
*.jsr.co.jp/*
*.jsgc.co.jp/*
*.jsf.co.jp/*
*.jreast.co.jp/*
*.jr-central.co.jp/*
*.jpower.co.jp/*
*.jp.nsk.com/*
*.jp.horiba.com/*
*.joyobank.co.jp/*
*.jowa-hd.co.jp/*
*.jot.co.jp/*
*.joshin.co.jp/*
*.joban-kosan.com/*
*.jms.cc/*
*.jmdm.co.jp/*
*.jkhd.co.jp/*
*.jgc.co.jp/*
*.jfe-shoji-hd.co.jp/*
*.jfe-holdings.co.jp/*
*.jeol.co.jp/*
*.jem-net.co.jp/*
*.jeansmate.co.jp/*
*.jdl.co.jp/*
*.jdc.co.jp/*
*.jcu-i.com/*
*.jcm.co.jp/*
*.jcm-hq.co.jp/*
*.jbr.co.jp/*
*.jbis-hd.com/*
*.jbcchd.co.jp/*
*.jastec.co.jp/*
*.japex.co.jp/*
*.japanfoods.co.jp/*
*.janome.co.jp/*
*.jalux.com/*
*.jaic-vc.co.jp/*
*.jafec.co.jp/*
*.jafco.co.jp/*
*.jae.co.jp/*
*.jaccs.co.jp/*
*.j-oil.com/*
*.j-front-retailing.com/*
*.izutsuya.co.jp/*
*.izumiya.co.jp/*
*.izumi.co.jp/*
*.iyobank.co.jp/*
*.iwatsu.co.jp/*
*.iwatebank.co.jp/*
*.iwatani.co.jp/*
*.iwasaki.co.jp/*
*.iwaki-kk.co.jp/*
*.iwaicosmo-hd.jp/*
*.itoki.jp/*
*.itoham.co.jp/*
*.itoen.co.jp/*
*.itochu.co.jp/*
*.itochu-shokuhin.com/*
*.itholdings.co.jp/*
*.itfor.co.jp/*
*.itcnetwork.co.jp/*
*.itcenex.com/*
*.isuzu.co.jp/*
*.iskweb.co.jp/*
*.isid.co.jp/*
*.ishizuka.co.jp/*
*.ishiss.co.jp/*
*.ishii-iiw.co.jp/*
*.iseki.co.jp/*
*.irom-hd.co.jp/*
*.ir-aiful.com/*
*.inx.co.jp/*
*.inuiship.co.jp/*
*.internix.co.jp/*
*.intage.co.jp/*
*.inpex.co.jp/*
*.innotech.co.jp/*
*.inet.co.jp/*
*.ines.co.jp/*
*.inageya.co.jp/*
*.inabata.co.jp/*
*.inaba.co.jp/*
*.inaba-ss.co.jp/*
*.impressholdings.com/*
*.imhds.co.jp/*
*.imasen.co.jp/*
*.ikyu.co.jp/*
*.ikont.co.jp/*
*.ikegami.co.jp/*
*.ik-felt.co.jp/*
*.iino.co.jp/*
*.iij.ad.jp/*
*.iidasangyo.co.jp/*
*.ihi.co.jp/*
*.iharachem.co.jp/*
*.idemitsu.co.jp/*
*.idec.com/*
*.icom.co.jp/*
*.ichiyoshi.co.jp/*
*.ichinen.co.jp/*
*.ichikoh.com/*
*.ichiken.co.jp/*
*.ichibanya.co.jp/*
*.ibjl.co.jp/*
*.ibiden.co.jp/*
*.hyakugo.co.jp/*
*.hurxley.co.jp/*
*.hulic.co.jp/*
*.hoya.co.jp/*
*.howa.co.jp/*
*.hosokawamicron.co.jp/*
*.hosiden.co.jp/*
*.hoshizaki.co.jp/*
*.horipro.co.jp/*
*.hoosiers.co.jp/*
*.honeys.co.jp/*
*.honda.co.jp/*
*.hokushinmdf.co.jp/*
*.hokuhoku-fg.co.jp/*
*.hokuetsubank.co.jp/*
*.hokuetsu-kishu.jp/*
*.hokto-kinoko.co.jp/*
*.hokkokubank.co.jp/*
*.hokkochem.co.jp/*
*.hokkanholdings.co.jp/*
*.hokkaido-gas.co.jp/*
*.hohsui.co.jp/*
*.hogy.co.jp/*
*.hodogaya.co.jp/*
*.hochiki.co.jp/*
*.hnhd.co.jp/*
*.hitachizosen.co.jp/*
*.hitachi.co.jp/*
*.hitachi-tool.co.jp/*
*.hitachi-metals.co.jp/*
*.hitachi-medical.co.jp/*
*.hitachi-kokusai.co.jp/*
*.hitachi-koki.co.jp/*
*.hitachi-kenki.co.jp/*
*.hitachi-hitec.com/*
*.hitachi-hb.co.jp/*
*.hitachi-chem.co.jp/*
*.hitachi-capital.co.jp/*
*.hitachi-cable.co.jp/*
*.hisamitsu.co.jp/*
*.hisaka.co.jp/*
*.his-j.com/*
*.hirose.co.jp/*
*.hirogin.co.jp/*
*.hioki.co.jp/*
*.hino.co.jp/*
*.himegin.co.jp/*
*.hikkoshi-sakai.co.jp/*
*.hikari.co.jp/*
*.higobank.co.jp/*
*.higashi-nipponbank.co.jp/*
*.hiday.co.jp/*
*.hibiya-eng.co.jp/*
*.hewtech.co.jp/*
*.hepco.co.jp/*
*.heliostec-hd.co.jp/*
*.heiwanet.co.jp/*
*.heiwado.jp/*
*.heiwa-net.co.jp/*
*.hdk.co.jp/*
*.hd.jx-group.co.jp/*
*.hc-kohnan.com/*
*.hazama.co.jp/*
*.hayashikane.co.jp/*
*.haseko.co.jp/*
*.haruyama.co.jp/*
*.harima.co.jp/*
*.hardoff.co.jp/*
*.hap-net.com/*
*.hanwa.co.jp/*
*.hamakyorex.co.jp/*
*.hakuyosha.co.jp/*
*.hakuto.co.jp/*
*.hakuhodody-holdings.co.jp/*
*.hakudo.co.jp/*
*.h2o-retailing.co.jp/*
*.gunze.co.jp/*
*.gunmabank.co.jp/*
*.gunei-chemical.co.jp/*
*.gsi.co.jp/*
*.gs-yuasa.com/*
*.gree.co.jp/*
*.gourmet-kineya.co.jp/*
*.goldwin.co.jp/*
*.goldcrest.co.jp/*
*.gogin.co.jp/*
*.godo-steel.co.jp/*
*.gnavi.co.jp/*
*.gmo.jp/*
*.gmo-pg.com/*
*.glv.co.jp/*
*.glory.co.jp/*
*.globeride.co.jp/*
*.glico.co.jp/*
*.ghs-inc.co.jp/*
*.geonet.co.jp/*
*.genkisushi.co.jp/*
*.gecoss.co.jp/*
*.gasukai.co.jp/*
*.gakken.co.jp/*
*.g-7holdings.co.jp/*
*.future.co.jp/*
*.futabasangyo.com/*
*.futaba.co.jp/*
*.fuso-pharm.co.jp/*
*.furusato.co.jp/*
*.furukawakk.co.jp/*
*.furukawadenchi.co.jp/*
*.furukawa.co.jp/*
*.furukawa-sky.co.jp/*
*.funaisoken.co.jp/*
*.funai.jp/*
*.fullcast.co.jp/*
*.fukutsu.co.jp/*
*.fukusima.co.jp/*
*.fukushimabank.co.jp/*
*.fukuoka-fg.com/*
*.fukuibank.co.jp/*
*.fukoku-rubber.co.jp/*
*.fujiya-peko.co.jp/*
*.fujitv.co.jp/*
*.fujitsu-general.com/*
*.fujitec.co.jp/*
*.fujita-kanko.co.jp/*
*.fujiseal.co.jp/*
*.fujioil.co.jp/*
*.fujimiinc.co.jp/*
*.fujikyu.co.jp/*
*.fujikurarubber.com/*
*.fujikura.co.jp/*
*.fujikiko-group.co.jp/*
*.fujifilmholdings.com/*
*.fujielectric.co.jp/*
*.fujiele.co.jp/*
*.fujicco.co.jp/*
*.fujibo.co.jp/*
*.fuji-jutaku.co.jp/*
*.fudotetra.co.jp/*
*.ftech.co.jp/*
*.fsi.co.jp/*
*.francebed-hd.co.jp/*
*.fpco.co.jp/*
*.foster.co.jp/*
*.fkoil.co.jp/*
*.fkkasei.co.jp/*
*.fkd.co.jp/*
*.firstship.co.jp/*
*.filcon.co.jp/*
*.fielding.co.jp/*
*.fidec.co.jp/*
*.fidea.co.jp/*
*.fhi.co.jp/*
*.fgl.co.jp/*
*.felt.co.jp/*
*.felissimo.co.jp/*
*.fdk.co.jp/*
*.fcc-net.co.jp/*
*.fastretailing.com/*
*.fanuc.co.jp/*
*.fantasy.co.jp/*
*.fancl.co.jp/*
*.family.co.jp/*
*.falco.co.jp/*
*.faith.co.jp/*
*.fa-aqua.co.jp/*
*.exeo.co.jp/*
*.exedy.co.jp/*
*.excelweb.co.jp/*
*.espec.co.jp/*
*.eslead.co.jp/*
*.epson.jp/*
*.eps.co.jp/*
*.enshu.co.jp/*
*.enplas.co.jp/*
*.energia.co.jp/*
*.emori.co.jp/*
*.elpida.com/*
*.elematec.com/*
*.ekk.co.jp/*
*.ejk.co.jp/*
*.eizo.co.jp/*
*.eisai.co.jp/*
*.eiken.co.jp/*
*.edion.co.jp/*
*.econach.co.jp/*
*.eco-s.co.jp/*
*.echotd.co.jp/*
*.ebara.co.jp/*
*.earth-chem.co.jp/*
*.eaccess.net/*
*.dynic.co.jp/*
*.dydo.co.jp/*
*.duskin.co.jp/*
*.dts.co.jp/*
*.ds-pharma.co.jp/*
*.drug-sugi.co.jp/*
*.drk.co.jp/*
*.dreamincubator.co.jp/*
*.dowa.co.jp/*
*.doshisha.co.jp/*
*.donki.com/*
*.dnt.co.jp/*
*.dnp.co.jp/*
*.dks-web.co.jp/*
*.djk.co.jp/*
*.disco.co.jp/*
*.dik-net.com/*
*.dijet.co.jp/*
*.digitalhearts.co.jp/*
*.did-daido.co.jp/*
*.dic.co.jp/*
*.descente.co.jp/*
*.denyo.co.jp/*
*.dentsu.co.jp/*
*.denso.co.jp/*
*.densetsuko.co.jp/*
*.denkikogyo.co.jp/*
*.denka.co.jp/*
*.dena.jp/*
*.dcm-hldgs.co.jp/*
*.danto-holdings.co.jp/*
*.daiyu8.co.jp/*
*.daiwaodakyu.co.jp/*
*.daiwahouse.co.jp/*
*.daiwabo.co.jp/*
*.daiwa-grp.jp/*
*.daitron.co.jp/*
*.daitobo.co.jp/*
*.daitobank.co.jp/*
*.daisyo.co.jp/*
*.daisue.co.jp/*
*.daiso-co.com/*
*.daishi-bank.co.jp/*
*.daiseki.co.jp/*
*.daiseki-eco.co.jp/*
*.daisanbank.co.jp/*
*.daiohs.com/*
*.daio-paper.co.jp/*
*.dainichi-net.co.jp/*
*.daikyo.co.jp/*
*.daikoku.co.jp/*
*.daiko-sb.co.jp/*
*.daikin.co.jp/*
*.daiken.jp/*
*.daiichisankyo.co.jp/*
*.daiichipan.co.jp/*
*.daiho.co.jp/*
*.daihen.co.jp/*
*.daihatsu.co.jp/*
*.daifuku.co.jp/*
*.daiei.co.jp/*
*.daidometal.com/*
*.daidoh-limited.com/*
*.daido.co.jp/*
*.daidan.co.jp/*
*.daicolor.co.jp/*
*.daicel.com/*
*.daibiru.co.jp/*
*.dai-ichi-life.co.jp/*
*.cybernet.co.jp/*
*.cvs-bayarea.co.jp/*
*.ctl.co.jp/*
*.ctie.co.jp/*
*.ctc-g.co.jp/*
*.cresco.co.jp/*
*.createsdhd.co.jp/*
*.createmedic.co.jp/*
*.cosmospc.co.jp/*
*.cosmo-oil.co.jp/*
*.cosel.co.jp/*
*.corona.co.jp/*
*.core.co.jp/*
*.conveyor.co.jp/*
*.comsys-hd.co.jp/*
*.colowide.co.jp/*
*.cocokarafine.co.jp/*
*.co-op.co.jp/*
*.co-jsp.co.jp/*
*.cmp.co.jp/*
*.cmk-corp.com/*
*.cmic.co.jp/*
*.clarion.com/*
*.ckk-chugoku.co.jp/*
*.ckd.co.jp/*
*.citizen.co.jp/*
*.circleksunkus.jp/*
*.cij.co.jp/*
*.ci-labo.com/*
*.chukyo-bank.co.jp/*
*.chugin.co.jp/*
*.chugai.co.jp/*
*.chugai-pharm.co.jp/*
*.chuetsu-pulp.co.jp/*
*.chudenko.co.jp/*
*.chuden.co.jp/*
*.chubushiryo.co.jp/*
*.chori.co.jp/*
*.chofu.co.jp/*
*.chkk.co.jp/*
*.chiyodagrp.co.jp/*
*.chiyoda-i.co.jp/*
*.chiyoda-corp.com/*
*.chino.co.jp/*
*.chikkarin.co.jp/*
*.chibakogyo-bank.co.jp/*
*.chibabank.co.jp/*
*.chi-group.co.jp/*
*.chemiphar.co.jp/*
*.chemi-con.co.jp/*
*.cgco.co.jp/*
*.cfs-corp.jp/*
*.central.co.jp/*
*.cec-ltd.co.jp/*
*.ccwest.co.jp/*
*.cccj.co.jp/*
*.cawachi.co.jp/*
*.casio.co.jp/*
*.carlit.co.jp/*
*.carbon.co.jp/*
*.carbide.co.jp/*
*.capcom.co.jp/*
*.canon-elec.co.jp/*
*.cando-web.co.jp/*
*.canare.co.jp/*
*.calsonickansei.co.jp/*
*.calbee.co.jp/*
*.cac.co.jp/*
*.bunka-s.co.jp/*
*.brother.co.jp/*
*.bridgestone.co.jp/*
*.bp.com/*
*.boy.co.jp/*
*.bookoff.co.jp/*
*.bond.co.jp/*
*.bml.co.jp/*
*.biccamera.co.jp/*
*.bestdenki.ne.jp/*
*.benesse-hd.co.jp/*
*.belluna.co.jp/*
*.bando.co.jp/*
*.bandainamco.co.jp/*
*.bals.co.jp/*
*.azumaship.co.jp/*
*.axell.co.jp/*
*.awi.co.jp/*
*.awabank.co.jp/*
*.avex.co.jp/*
*.autobacs.co.jp/*
*.atsugi.co.jp/*
*.atk-dk.co.jp/*
*.astellas.com/*
*.askul.co.jp/*
*.aska-pharma.co.jp/*
*.asics.co.jp/*
*.ashimori.co.jp/*
*.asax.co.jp/*
*.asanuma.co.jp/*
*.asahitec.co.jp/*
*.asahikogyosha.co.jp/*
*.asahiholdings.com/*
*.asahidia.co.jp/*
*.asahibeer.co.jp/*
*.asahi-yukizai.co.jp/*
*.asahi-kasei.co.jp/*
*.as-1.co.jp/*
*.arrk.co.jp/*
*.arnest1.co.jp/*
*.arisawa.co.jp/*
*.ariakejapan.com/*
*.argo-graph.co.jp/*
*.arcs-g.co.jp/*
*.arcland.co.jp/*
*.araya-kk.co.jp/*
*.arakawachem.co.jp/*
*.aozorabank.co.jp/*
*.aoyama-syouji.co.jp/*
*.aoki-hd.co.jp/*
*.aoi-pro.com/*
*.aochd.co.jp/*
*.anritsu.co.jp/*
*.anest-iwata.co.jp/*
*.ando-corp.co.jp/*
*.ana.co.jp/*
*.amuse.co.jp/*
*.amiyakitei.co.jp/*
*.amano.co.jp/*
*.amada.co.jp/*
*.altech.co.jp/*
*.alsok.co.jp/*
*.alpsgiken.co.jp/*
*.alps.com/*
*.alpine.com/*
*.alpha.co.jp/*
*.alpen-group.jp/*
*.alfresa.com/*
*.akita-bank.co.jp/*
*.akebono-brake.com/*
*.ajinomoto.co.jp/*
*.aisin.co.jp/*
*.aisan-ind.co.jp/*
*.airtech.co.jp/*
*.aiphone.co.jp/*
*.ainj.co.jp/*
*.aiholdings.co.jp/*
*.aigan.co.jp/*
*.aida.co.jp/*
*.aichitokei.co.jp/*
*.aichikikai.co.jp/*
*.aichibank.co.jp/*
*.aichi-steel.co.jp/*
*.aichi-corp.co.jp/*
*.aica.co.jp/*
*.agrex.co.jp/*
*.agc.com/*
*.afc-group.jp/*
*.aeonmall.com/*
*.aeondelight.co.jp/*
*.aeoncredit.co.jp/*
*.aeon.info/*
*.aeon-hokkaido.jp/*
*.advantest.co.jp/*
*.advanex.co.jp/*
*.advan.co.jp/*
*.adk.jp/*
*.aderans.jp/*
*.adeka.co.jp/*
*.acom.co.jp/*
*.achilles.jp/*
*.accretech.jp/*
*.accordiagolf.com/*
*.abc-mart.com/*
*.aandd.co.jp/*
*.aaconst.co.jp/*
*.a-bank.jp/*
*.82bank.co.jp/*
*.7andi.com/*
*.77bank.co.jp/*
*.24028.jp/*
*.18bank.co.jp/*
*.114bank.co.jp/*
*.0101maruigroup.co.jp/*

# Broken Site
net-cash.jp/*

{+block{/}}
# tracking cookie ####################################
#<script type="text/javascript" src="http://pranking6.ziyu.net/js/tvdorama.js" charset="euc-jp"></script>
*.ziyu.net/js/*

#var kauli_yad_count = typeof(kauli_yad_count) == 'undefined' ? 1 : kauli_yad_count + 1;
#(function(d){ d.write('<span id="kauli_yad_' + kauli_yad_count + '" style="width:728px; 
#height:90px; display:inline-block"><!--22291--><' + '/span>'); 
#var s = d.createElement('script'); var h = d.getElementsByTagName('head')[0]; 
#s.defer = 'defer'; s.async = 'async'; s.src = 'http://js.kau.li/yad.js'; 
#h.insertBefore(s, h.firstChild);})(document);
*.kau.li/*

#<script type="text/javascript" src="http://garss.tv/user/1120504211/display.php?id=1120504211"></script>
garss.tv/user/*

#<script type="text/javascript" src="http://az.trackword.net/show.phtml?r=douga119-anime" charset="utf-8"></script>
*.trackword.net/show.phtml

#<script language="javascript" src="http://analyzer52.fc2.com/ana/processor.php?uid=431249" type="text/javascript"></script>
#<script type="text/javascript" language="javascript" src="http://analyzer52.fc2.com/ana/analyzer.php?uid=431249&amp;pid=0&amp;idsess=&amp;ref=&amp;href=http%3A//tumakan.blog66.fc2.com/blog-category-34.html&amp;wid=1024&amp;hei=768&amp;col=32&amp;visitor=1-1026751728-1340013246-0-1-1-0&amp;ssl=0" charset="UTF-8"></script>
analyzer*.fc2.com/ana/*

#<script src="http://rc5.i2i.jp/view/viewimp.php?00401937&amp;js&amp;&amp;&amp;&amp;69" type="text/javascript"></script>
rc*.i2i.jp/view/*

#<script type="text/javascript" charset="utf-8" src="http://www2.liveads.jp/widgets/ec/fashion_walker/03/liveads.js"></script>
*.liveads.jp/widgets/*

#<script type="text/javascript">NH=NINhostname; document.write(unescape("%3Cscript src='http://script.trackword.net/horizontal.js#matodoga' charset='utf-8' type='text/javascript'%3E%3C/script%3E"));</script>
script.trackword.net/*

#<script type="text/javascript" src="http://seoparts.com/u.js?1/5/" charset="euc-jp"></script>
seoparts.com/u.js

#<img style="width:80px;height:9px;" width="80" height="9" src="http://j1.ax.xrea.com/x.gif" border="0">
*.ax.xrea.com/

#<script type="text/javascript" src="http://code.dumbo.shinobi.jp/ninja_ar/Script?id=00001287&amp;hash=f18f1f7c"></script>
#<script type="text/javascript" src="http://code.analysis.shinobi.jp/ninja_ar/Script?id=00030562&amp;hash=86441cc8"></script>
code.*.shinobi.jp/*

#<script type="text/javascript" src="http://x6.bokunenjin.com/ufo/083591400"></script>
*.bokunenjin.com/ufo/*

#<script src="http://x6.bokunenjin.com/Zen?0835914Naaabaaabaaaaaaaaaaaaaabnkbdobgh00__http://j.plustar.jp/" defer=""></script>
*.bokunenjin.com/Zen

#<script src="http://widget.zenback.jp/?base_uri=http%3A//fxya.blog129.fc2.com/&amp;nsid=90532518536721452%3A%3A90532531421605520&amp;rand=739099015277" type="text/javascript"></script>
widget.zenback.jp/?base_uri

# ad #################################################
#<a href="http://serv.ads.pixiv.org/click.php?banner_id=8512&amp;page_id=withoutmypage&amp;url=http%3A%2F%2Fwww.kfsnet.co.jp%2Fattow%2F" target="_blank">
#  <img src="http://img.ads.pixiv.org/img/BN0000008512_1334056737.gif" width="468" height="60" border="0">
#</a>
img.ads.pixiv.org/img/*

#<script language="JavaScript1.1" src="http://ngs.impress.co.jp/js.ng/site=WF&amp;size=728x90&amp;sp=super?ord=355223">
#</script>
#<script>
#bust = Math.floor(1000000*Math.random());
#document.write('<scr'+'ipt language="JavaScript1.1" src="http://ngs.impress.co.jp/js.ng/site=WF&size=728x90&sp=super?ord='+bust+'">\n');
#document.write('</scr'+'ipt>');</script>
ngs.impress.co.jp/js.ng/*

#<script type="text/javascript" language="JavaScript">
#	become_partner    = "bj_dailysports_public";
#	become_css_type   = "ORAPI300x250II";
#	become_image_size = 100;
#	become_genre      = "dailysports_001";
#	become_prd_num    = 2;
#	become_win_width  = 298;
#	become_win_height = 248;
#	become_border     = 1;
#	become_border_color = "#F39800";
#</script>
#<script type="text/javascript" language="JavaScript" src="http://partner.become.co.jp/js/showhtml.js"></script>
partner.become.co.jp/js/*

{-filter{adl_s}}

{-filter{ana_a}}
www.navitime.co.jp/*
