/*
 * extrapper.js - JavaScript for ExTrapper
 * (c) 2006-2010 Plustar Co. Ltd.
 * All rights reserved.
 */

var ICON_PATH="lib/images/icons";
var HELPPAGE_URL="http://www.plustar.jp/trapper/help.php?id=";
var CONTACT_URL="http://www.plustar.jp/contact/report.php?p=ext_res&t=";
var DEFAULT_INTERVAL=30;
Ext.BLANK_IMAGE_URL="lib/images/s.gif";
Ext.QuickTips.init();
var G={main_wnd:{grid:null,proc_count:0,conn_count:0},proc_dlg:null,sshot_dlg:null,opt_dlg:null,lic_dlg:null,pwd_prompt:null,log_dlg:null,net_dlg:null,amachine_dlg:null,machine_dlg:null,install_dlg:null,url_dlg:null,transcope_dlg:null,wakeup_dlg:null,updatehistory_dlg:null};
function build_license_dialog(){if(!G.lic_dlg){var b=function(){G.lic_dlg.hide()};
var a=new Ext.Window({title:"ライセンス情報",iconCls:"btn-key",applyTo:"lic-dlg",layout:"fit",animateTarget:"act-btn-help",autoScroll:false,autoCreate:true,resizable:false,bodyBorder:false,closeAction:"hide",closable:false,modal:true,plain:true,height:350,width:450,proxyDrag:true,shadow:false,shadowOffset:10,border:false,html:"",items:[],buttons:[{text:"閉じる",handler:function(){b()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){b()}}]});
a.body.on({click:{stopEvent:true,delegate:"a",fn:handler.open_window}});
G.lic_dlg=a}return G.lic_dlg}function build_log_dialog(){if(!G.log_dlg){var c=new Ext.data.JsonStore({url:"/log",storeId:"dy",sortInfo:{field:"dy",direction:"DESC"},fields:[{name:"dy",type:"string"},{name:"hn",type:"string"},{name:"ip",type:"string"},{name:"sn",type:"string"},{name:"kg",type:"string"}]});
var a=new Ext.grid.ColumnModel([{id:"col-dy",header:"停止日",dataIndex:"dy",width:150,align:"right",sortable:true},{header:"マシン名",dataIndex:"hn",width:90,align:"left",sortable:true},{header:"IP",dataIndex:"ip",width:90,align:"left",sortable:true},{header:"ソフト名",dataIndex:"sn",width:150,align:"left",sortable:true},{header:"停止",dataIndex:"kg",width:20,align:"left",sortable:true,renderer:function(f){switch(f){case"pc_stop":return'<img src="'+ICON_PATH+'/ue.png" alt="自動" title="自動" />';
case"ad_stop":return'<img src="'+ICON_PATH+'/sy.png" alt="手動" title="手動" />';
default:return'<img src="'+ICON_PATH+'/de.png" alt="自動" title="自動" />'}}}]);
a.defaultSortable=true;
var b=new Ext.grid.GridPanel({region:"center",border:false,ds:c,cm:a,autoExpandColumn:"dy",viewConfig:{forceFit:true},height:340,width:495,loadMask:{msg:"プロセスデータ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(f){c.load()}});
var e=function(){G.log_dlg.hide();
G.log_dlg=null};
var d=new Ext.Window({animateTarget:"act-btn-tools",iconCls:"btn-log",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:410,width:550,modal:true,proxyDrag:true,shadow:true,shadowOffset:10,constrain:true,items:[b],tbar:[{cls:"x-btn-text-icon",text:"停止プロセス検索",icon:ICON_PATH+"/zm.png",tooltip:"停止プロセス名の検索を行います",handler:onStopProcessSearch,scope:this}],buttons:[{text:"閉じる",handler:function(){e()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){e()}}]});
b.on("rowdblclick",function(g,f,h){window.open("http://www.plustar.jp/proc.php?q="+g.getStore().getAt(f).get("sn"),"google_search")});
b.switch_target();
d.grid=b;
d.ds=c;
G.log_dlg=d}else{G.log_dlg=null}return G.log_dlg}function onStopProcessSearch(){var a=G.log_dlg.grid.getSelectionModel().getSelected();
if(!a){Ext.MessageBox.show({title:"メッセージ",msg:"検索するプロセスを選択してください。",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});
return}var b=a.get("sn");
window.open("http://www.plustar.jp/proc.php?q="+b,"google_search")}function build_process_dialog(b,c){if(!G.proc_dlg){var e=new Ext.data.JsonStore({url:"/process",autoLoad:true,baseParams:{macaddr:c},storeId:"pid",sortInfo:{field:"pid",direction:"ASC"},fields:[{name:"pid",type:"int"},{name:"sid",type:"int"},{name:"procname",type:"string"},{name:"begin",type:"date"},{name:"time_span",type:"string"}]});
var a=new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(),{id:"col-procname",header:"イメージ名",dataIndex:"procname",width:100,sortable:true},{header:"PID",dataIndex:"pid",width:35,align:"right",sortable:true},{header:"ID",dataIndex:"sid",width:20,align:"right",sortable:true},{header:"起動日時",dataIndex:"begin",width:110,renderer:Ext.util.Format.dateRenderer("Y/m/d H:i:s"),sortable:true},{header:"経過時間",dataIndex:"time_span",width:60,align:"right",sortable:true}]);
a.defaultSortable=true;
var d=new Ext.grid.GridPanel({region:"center",border:false,ds:e,cm:a,autoExpandColumn:"pid",viewConfig:{forceFit:true},height:340,width:455,loadMask:{msg:"プロセスデータ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(h){e.load()}});
var g=function(){G.proc_dlg.hide();
G.proc_dlg=null};
var f=new Ext.Window({animateTarget:"act-btn-procs",iconCls:"btn-proc",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:410,width:450,modal:true,proxyDrag:true,shadow:true,shadowOffset:10,constrain:true,items:[d],tbar:[{id:"act-btn-proc",cls:"x-btn-text-icon",text:"停止",icon:ICON_PATH+"/st.png",tooltip:"選択したプロセスを停止します",handler:onProcessStop,scope:this},{cls:"x-btn-text-icon",text:"更新",icon:ICON_PATH+"/ah.png",tooltip:"プロセス一覧を更新します",handler:function(){e.load()},scope:this},"-",{cls:"x-btn-text-icon",text:"プロセス検索",icon:ICON_PATH+"/zm.png",tooltip:"プロセス名の検索を行います",handler:onProcessSearch,scope:this}],buttons:[{text:"閉じる",handler:function(){g()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){g()}}]});
d.on("rowdblclick",function(i,h,j){window.open("http://www.plustar.jp/proc.php?q="+i.getStore().getAt(h).get("procname"),"google_search")});
f.grid=d;
f.ds=e;
G.proc_dlg=f}else{G.proc_dlg=null}return G.proc_dlg}function onProcessStop(){var a=G.proc_dlg.grid.getSelectionModel().getSelected();
if(!a){Ext.MessageBox.show({title:"メッセージ",msg:"停止するプロセスを選択してください。",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});
return}var c=a.get("procname");
var b=c.toLowerCase();
if(b=="[system process]"||b=="csrss.exe"||b=="lsass.exe"||b=="pextrapper.exe"||b=="ppower.exe"||b=="ptools.exe"||b=="services.exe"||b=="smss.exe"||b=="spoolsv.exe"||b=="svchost.exe"||b=="system"||b=="winlogon.exe"||b=="pcontroler.exe"||b=="pcheckwindow.exe"){Ext.MessageBox.show({title:"警告",msg:c+'は停止できません。<br>停止するとシステムが不安定になります。<br><a href="'+HELPPAGE_URL+"1&procname="+c+'" target="_blank">エラー詳細情報...</a>',width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR});
return}Ext.MessageBox.confirm("確認","プロセスを終了すると、データが失われたり、システムが不安定になったりするなどの、予期しない結果になることがあります。<br /><br />プロセスを終了する前に、状態またはデータを保存するかどうかの確認メッセージは表示されません。<br /><br />プロセスを終了しますか?",function(d){if(d=="yes"){G.proc_dlg.ds.load({params:{procname:a.get("procname")}})}})}function onProcessSearch(){var a=G.proc_dlg.grid.getSelectionModel().getSelected();
if(!a){Ext.MessageBox.show({title:"メッセージ",msg:"検索するプロセスを選択してください。",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});
return}var b=a.get("procname");
window.open("http://www.plustar.jp/proc.php?q="+b,"google_search")}function build_screenshot_password_prompt(){if(!G.pwd_prompt){var a='<span class="ext-mb-text">パスワードを入力してください。</span><br /><input type="password" class="ext-mb-input" id="sshot_pwd"/><br>&nbsp;
&nbsp;
<a href="'+HELPPAGE_URL+'4" target="_blank">詳細情報...</a>';
var b=new Ext.Window({id:"sshot-prompt",title:"認証",iconCls:"btn-sshot",closeAction:"hide",closable:false,shadow:true,draggable:true,resizable:false,fixedcenter:true,collapsible:false,shim:true,modal:true,width:300,height:135,layout:"fit",buttonAlign:"center",constrain:true,items:[{html:a}],buttons:[{text:"OK",handler:function(){if(b.isVisible()){pwd=Ext.get("sshot_pwd");
G.pwd_prompt.callback(pwd.getValue());
G.pwd_prompt.hide()}}},{text:"キャンセル",handler:function(){G.pwd_prompt.hide()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){G.pwd_prompt.hide();
G.pwd_prompt=null}},{key:Ext.EventObject.ENTER,handler:function(){if(b.isVisible()){pwd=Ext.get("sshot_pwd");
G.pwd_prompt.callback(pwd.getValue());
G.pwd_prompt.hide()}}}]});
b.show();
G.pwd_prompt=b}Ext.getDom("sshot_pwd").value="";
return G.pwd_prompt}function build_option_dialog(){if(!G.opt_dlg){var c=new Ext.TabPanel({region:"center",animScroll:true,enableTabScroll:true,deferredRender:false});
var h=new Ext.Window({applyTo:"opt-dlg",animateTarget:"act-btn-tools",iconCls:"btn-opt",closeAction:"hide",closable:false,width:360,height:400,minimizable:true,border:false,plain:true,layout:"border",modal:true,shadow:true,shadowOffset:10,autoScroll:false,resizable:false,proxyDrag:true,constrain:true,items:[c],buttons:[{text:"OK",handler:function(){c.getActiveTab().submit(true)}},{text:"キャンセル",handler:function(){G.opt_dlg.hide()}},{text:"適用",handler:function(){c.getActiveTab().submit()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){G.opt_dlg.hide()}}]});
h.on("minimize",function(){h.toggleCollapse()});
var a=build_suppression_grid(h);
a.submit=function(i){if(!a.updated){if(i){G.opt_dlg.hide()}return}var k=a.getStore();
var j=new Array();
var l="";
Ext.each(k.getRange(),function(s,m){var r=s.get("procname");
var q=r.toLowerCase();
if((q=="csrss.exe"||q=="lsass.exe"||q=="pextrapper.exe"||q=="ppower.exe"||q=="ptools.exe"||q=="services.exe"||q=="smss.exe"||q=="spoolsv.exe"||q=="svchost.exe"||q=="system"||q=="winlogon.exe"||q=="pcontroler.exe"||q=="pcheckwindow.exe")||(q.length<7)){l+=r+" "}if(q!==""){j[m]={procname:r}}});
if(l){Ext.MessageBox.show({title:"メッセージ",msg:String.format('{0}は起動禁止リストに追加できません。<br><a href="'+HELPPAGE_URL+'2&procname={0}" target="_blank">エラー詳細情報...</a>',l),width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.WARNING});
return}Ext.MessageBox.confirm("確認","指定したプロセスによっては、データが失われたり、システムが不安定になったりするなどの、予期しない結果になることがあります。<br /><br />プロセスを終了する前に、状態またはデータを保存するかどうかの確認メッセージは表示されません。<br /><br />起動禁止リストを保存しますか?",function(m){if(m=="yes"){Ext.MessageBox.alert("メッセージ","起動禁止リストを保存しました。",function(){if(i){G.opt_dlg.hide()}else{k.load({params:{data:Ext.encode(j)}});
a.updated=false;
h.buttons[2].disable()}})}})};
a.on({activate:{fn:function(){a.getView().refresh(true);
h.buttons[2].setDisabled(!a.updated)}},deactivate:{fn:function(){a.stopEditing()}}});
var e=build_sync_form(h);
e.submit=function(i){if(!e.updated){if(i){G.opt_dlg.hide()}return}e.form.submit({failure:function(j,k){},success:function(j,k){Ext.MessageBox.alert("メッセージ","同期サーバ設定を変更しました。",function(){if(i){G.opt_dlg.hide()}else{j.updated=false;
h.buttons[2].setDisabled(true)}})}})};
e.on({activate:{fn:function(){e.load();
h.buttons[2].setDisabled(!e.updated)}}});
var g=build_password_form(h);
g.submit=function(i){if(!g.updated){if(i){G.opt_dlg.hide()}return}g.form.submit({reset:true,scope:this,failure:function(j,k){},success:function(j,k){g.updated=false;
Ext.MessageBox.alert("メッセージ","パスワードを変更しました。",function(){if(i){G.opt_dlg.hide()}else{g.updated=false;
h.buttons[2].setDisabled(true)}})}})};
g.on({activate:function(){h.buttons[2].setDisabled(!g.updated)}});
var b=build_net_form(h);
b.submit=function(i){if(!b.updated){if(i){G.opt_dlg.hide()}return}b.form.submit({failure:function(j,k){},success:function(j,k){Ext.MessageBox.alert("メッセージ","ネットワーク設定を変更しました。",function(){if(i){G.opt_dlg.hide()}else{j.updated=false;
h.buttons[2].setDisabled(true)}})}})};
b.on({activate:{fn:function(){b.load();
h.buttons[2].setDisabled(!b.updated)}}});
var f=build_misc_form(h);
f.submit=function(i){if(!f.updated){if(i){G.opt_dlg.hide()}return}f.form.submit({scope:this,failure:function(k,j){},success:function(k,j){Ext.MessageBox.alert("メッセージ","一括設定を禁止リストに反映しました。",function(){if(i){G.opt_dlg.hide()}else{k.updated=false;
h.buttons[2].setDisabled(true);
a.switch_target()}})}})};
f.on({activate:{fn:function(){f.load();
h.buttons[2].setDisabled(!f.updated)}}});
var d=build_notice_form(h);
d.submit=function(i){if(!d.updated){if(i){G.opt_dlg.hide()}return}d.form.submit({scope:this,failure:function(j,k){},success:function(j,k){Ext.MessageBox.alert("メッセージ","通知設定を保存しました。",function(){if(i){G.opt_dlg.hide()}else{j.updated=false;
h.buttons[2].setDisabled(true)}})}})};
d.on({activate:{fn:function(){d.load();
h.buttons[2].setDisabled(!d.updated)}}});
c.add(a);
c.add(f);
c.add(e);
c.add(g);
c.add(b);
c.add(d);
c.setActiveTab(0);
G.opt_dlg=h}return G.opt_dlg}function build_password_form(b){if(!b.form_pwd){Ext.apply(Ext.form.VTypes,{password:function(c,d){if(d.initialPassField){var e=Ext.getCmp(d.initialPassField);
return(c==e.getValue())}return true},passwordText:"パスワードが一致しません。"});
var a=new Ext.FormPanel({frame:true,header:false,width:340,title:"パスワード",id:"tabs-password",iconCls:"tabs-password",autoDestroy:true,trackResetOnLoad:true,timeout:10,url:"/password",method:"POST",items:[{border:false,items:[{items:{labelWidth:10,xtype:"fieldset",title:"変更パスワード種別",height:90,defaultType:"radio",items:[{fieldLabel:"",boxLabel:"ログインパスワード",inputValue:"login",name:"password_type",labelSeparator:"",checked:true},{fieldLabel:"",boxLabel:"スクリーンショットパスワード",inputValue:"sshot",name:"password_type",labelSeparator:"",checked:false}]}}]},{xtype:"fieldset",labelWidth:140,title:"パスワード設定",height:120,defaultType:"textfield",layout:"form",items:[{fieldLabel:"現在のパスワード",name:"old_password",id:"old_password",inputType:"password",selectOnFocus:true,msgTarget:"side",allowBlank:false,width:125},{fieldLabel:"新しいパスワード",name:"new_password",id:"new_password",inputType:"password",selectOnFocus:true,msgTarget:"side",allowBlank:false,maxLength:15,minLength:5,width:125},{fieldLabel:"新しいパスワードを確認",name:"cfm_password",id:"cfm_password",inputType:"password",selectOnFocus:true,msgTarget:"side",allowBlank:false,maxLength:15,minLength:5,vtype:"password",initialPassField:"new_password",width:125}]}]});
a.render(document.body);
Ext.getCmp("old_password").on("change",function(e,c,d){a.updated=true;
b.buttons[2].enable()});
Ext.getCmp("new_password").on("change",function(e,c,d){a.updated=true;
b.buttons[2].enable()});
Ext.getCmp("cfm_password").on("change",function(e,c,d){a.updated=true;
b.buttons[2].enable()});
b.form_pwd=a}return b.form_pwd}function build_suppression_grid(f){if(!f.suppression_grid){var d=Ext.data.Record.create([{name:"procname",type:"string"}]);
var a=new Ext.grid.ColumnModel([{id:"suppression-col-procname",header:"起動禁止プロセス",dataIndex:"procname",resizable:false,width:200,sortable:true,editor:new Ext.form.TextField({allowBlank:false})}]);
var e=new Ext.data.JsonStore({url:"/suppression",sortInfo:{field:"procname",direction:"ASC"},fields:[{name:"procname",type:"string"}]});
e.on({add:function(h,i,g){f.suppression_grid.updated=true;
f.buttons[2].enable()},remove:function(h,i,g){f.suppression_grid.updated=true;
f.buttons[2].enable()},update:function(g,h,i){f.suppression_grid.updated=true;
f.buttons[2].enable()}});
var c=new Ext.ux.grid.RowEditor({saveText:"更新",cancelText:"キャンセル"});
var b=new Ext.grid.GridPanel({frame:true,title:"起動禁止リスト",id:"tabs-stop",iconCls:"tabs-stop",ds:e,cm:a,autoExpandColumn:"suppression-col-procname",selModel:new Ext.grid.RowSelectionModel({singleSelect:false}),enableColLock:false,enableColumnHide:false,frame:true,width:340,loadMask:{msg:"禁止リストデータ取得中..."},viewConfig:{forceFit:true},plugins:[c],switch_target:function(g){e.load()},tbar:[{cls:"x-btn-text-icon",text:"追加",icon:ICON_PATH+"/ad.png",tooltip:"項目を追加します",handler:function(){var g=new d({procname:""});
b.stopEditing();
e.insert(0,g);
b.startEditing(0,0)},scope:this},{id:"act-btn-proc",cls:"x-btn-text-icon",text:"削除",icon:ICON_PATH+"/de.png",tooltip:"選択した項目を削除します",handler:function(){var g=b.getSelectionModel().getSelected();
if(!g){Ext.MessageBox.show({title:"メッセージ",msg:"削除する項目を選択してください。",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});
return}Ext.each(g,function(i,h){e.remove(i)})},scope:this}],viewConfig:{forceFit:true}});
b.show();
b.switch_target();
f.suppression_grid=b}return f.suppression_grid}function build_misc_form(c){if(!c.form_misc){var b=new Ext.FormPanel({frame:true,header:false,title:"一括禁止設定",id:"tabs-etc",iconCls:"tabs-etc",width:340,labelWidth:0,trackResetOnLoad:true,timeout:10,url:"/misc",method:"POST",items:[{border:false,items:[{xtype:"fieldset",title:"タスクマネージャ系設定",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"起動許可",inputValue:1,name:"tm_type",id:"tm_allow"},{boxLabel:"起動禁止",inputValue:0,name:"tm_type",id:"tm_deny"}]}]},{xtype:"fieldset",title:"レジストリエディタ系設定",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"起動許可",inputValue:1,name:"re_type",id:"re_allow"},{boxLabel:"起動禁止",inputValue:0,name:"re_type",id:"re_deny"}]}]},{xtype:"fieldset",title:"ファイル共有系設定",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"起動許可",inputValue:1,name:"p2p_type",id:"p2p_allow"},{boxLabel:"起動禁止",inputValue:0,name:"p2p_type",id:"p2p_deny"}]}]}]}]});
var a=new Ext.data.JsonStore({url:"/misc",fields:["tm_type","re_type","p2p_type"]});
a.on("load",function(d,e,f){if(e[0].get("tm_type")){Ext.getCmp("tm_allow").setValue(true)}else{Ext.getCmp("tm_deny").setValue(true)}if(e[0].get("re_type")){Ext.getCmp("re_allow").setValue(true)}else{Ext.getCmp("re_deny").setValue(true)}if(e[0].get("p2p_type")){Ext.getCmp("p2p_allow").setValue(true)}else{Ext.getCmp("p2p_deny").setValue(true)}});
a.load();
b.render(document.body);
Ext.getCmp("tm_allow").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("tm_deny").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("re_allow").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("re_deny").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("p2p_allow").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("p2p_deny").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
c.form_misc=b}return c.form_misc}function build_notice_form(c){if(!c.form_notice){Ext.apply(Ext.form.VTypes,{ismail:function(d){return(d.match(/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/))},ismailText:"正しいメールアドレス形式ではありません。<br>例）info@plustar.jp"});
var b=new Ext.FormPanel({frame:true,header:false,title:"通知",id:"tabs-notice",iconCls:"tabs-notice",width:340,labelWidth:0,trackResetOnLoad:true,timeout:10,url:"/notice",method:"POST",items:[{border:false,items:[{xtype:"fieldset",title:"起動停止通知メッセージ",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"使用する",inputValue:1,name:"nc_pop",id:"pop_allow"},{boxLabel:"使用しない",inputValue:0,name:"nc_pop",id:"pop_deny"}]}]},{xtype:"fieldset",title:"起動停止通知メール送信",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"使用する",inputValue:1,name:"nc_mail",id:"mail_allow"},{boxLabel:"使用しない",inputValue:0,name:"nc_mail",id:"mail_deny"}]}]},{xtype:"fieldset",labelWidth:120,title:"通知メール送信先アドレス",height:60,defaultType:"textfield",layout:"form",items:[{fieldLabel:"アドレス",name:"nc_mailadd",id:"nc_mailadd",emptyText:"trapper@plustar.jp",selectOnFocus:true,msgTarget:"side",maxLength:55,minLength:7,allowBlank:true,vtype:"ismail",width:155}]},{xtype:"fieldset",title:"アラート音源設定",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"Wave",inputValue:0,name:"alert_type",id:"alert_wav"},{boxLabel:"Beep",inputValue:1,name:"alert_type",id:"alert_beep"}]}]}]}]});
var a=new Ext.data.JsonStore({url:"/notice",fields:["nc_pop","nc_mail","nc_mailadd","alert_type"]});
a.on("load",function(e,f,g){if(f[0].get("nc_pop")){Ext.getCmp("pop_allow").setValue(true)}else{Ext.getCmp("pop_deny").setValue(true)}if(f[0].get("nc_mail")){Ext.getCmp("mail_allow").setValue(true)}else{Ext.getCmp("mail_deny").setValue(true)}var d=f[0].get("nc_mailadd");
if(d!==""){Ext.getCmp("nc_mailadd").setValue(d)}else{Ext.getCmp("nc_mailadd").setValue("")}if(f[0].get("alert_type")){Ext.getCmp("alert_beep").setValue(true)}else{Ext.getCmp("alert_wav").setValue(true)}});
a.load();
b.render(document.body);
Ext.getCmp("pop_allow").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("pop_deny").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("mail_allow").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("mail_deny").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("nc_mailadd").on("change",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("alert_wav").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("alert_beep").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
c.form_notice=b}return c.form_notice}function build_net_form(c){if(!c.form_net){var b=new Ext.FormPanel({frame:true,header:false,title:"ネットワーク設定",id:"tabs-net",iconCls:"tabs-net",width:340,labelWidth:0,trackResetOnLoad:true,timeout:10,url:"/net",method:"POST",items:[{labelWidth:0,border:false,items:[{xtype:"fieldset",title:"回線切断監視設定",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"使用する",inputValue:1,name:"net_con",id:"use_con"},{boxLabel:"使用しない",inputValue:0,name:"net_con",id:"duse_con"}]}]},{labelWidth:0,xtype:"fieldset",title:"回線負荷監視設定",autoHeight:true,items:[{xtype:"radiogroup",fieldLabel:"",labelSeparator:"",labelWidth:0,items:[{boxLabel:"使用する",inputValue:1,name:"net_mon",id:"use_mon"},{boxLabel:"使用しない",inputValue:0,name:"net_mon",id:"duse_mon"}]}]},{xtype:"fieldset",labelWidth:140,title:"回線負荷警告レベル",height:90,defaultType:"textfield",layout:"form",items:[{fieldLabel:"警告レベル(%)<br>150-999%まで設定可能<br>200%通常の2倍の負荷",name:"net_alt",id:"net_alt",selectOnFocus:true,msgTarget:"side",maxLength:3,minLength:3,allowBlank:false,width:30}]}]}]});
b.render(document.body);
var a=new Ext.data.JsonStore({url:"/net",fields:["mon","con","alt"]});
a.on("load",function(d,e,g){if(e[0].get("mon")){Ext.getCmp("use_mon").setValue(true)}else{Ext.getCmp("duse_mon").setValue(true)}if(e[0].get("con")){Ext.getCmp("use_con").setValue(true)}else{Ext.getCmp("duse_con").setValue(true)}var f=e[0].get("alt");
if(f!==""){Ext.getCmp("net_alt").setValue(f)}else{Ext.getCmp("net_alt").setValue("300")}});
a.load();
b.render(document.body);
Ext.getCmp("use_mon").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("duse_mon").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("use_con").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("duse_con").on("focus",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
Ext.getCmp("net_alt").on("change",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
c.form_net=b}return c.form_net}function build_sync_form(c){if(!c.form_sync){Ext.apply(Ext.form.VTypes,{isip:function(d){return(d.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/))},isipText:"IPアドレス形式ではありません。<br>例）192.168.1.1"});
var b=new Ext.FormPanel({frame:true,header:false,title:"同期",id:"tabs-sync",iconCls:"tabs-sync",width:340,labelWidth:0,trackResetOnLoad:true,timeout:10,url:"/sync",method:"POST",items:[{border:false,items:[{xtype:"fieldset",labelWidth:140,title:"同期サーバ設定",height:60,defaultType:"textfield",layout:"form",items:[{fieldLabel:"同期サーバ",name:"sync_server",id:"sync_server",emptyText:"サーバアドレス",selectOnFocus:true,msgTarget:"side",maxLength:15,minLength:7,allowBlank:true,vtype:"isip",width:120}]}]}]});
var a=new Ext.data.JsonStore({url:"/sync",fields:["server"]});
a.on("load",function(d,e,g){var f=e[0].get("server");
if(f!==""){Ext.getCmp("sync_server").setValue(f)}else{Ext.getCmp("sync_server").setValue("")}});
a.load();
b.render(document.body);
Ext.getCmp("sync_server").on("change",function(g,d,e){b.updated=true;
c.buttons[2].enable()});
c.form_sync=b}return c.form_sync}function build_machine_list_dialog(){if(!G.amachine_dlg){var a=new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(),{id:"hostname",header:"ホスト名",dataIndex:"hostname",width:120,sortable:true},{header:"IPアドレス",dataIndex:"ipaddr",width:85,align:"right",sortable:true},{header:"MACアドレス",dataIndex:"macaddr",width:90,align:"right",sortable:true},{header:"CPU",dataIndex:"cpu",width:200,sortable:true},{header:"グラボ",dataIndex:"grabo",width:200,sortable:true},{header:"メモリ",dataIndex:"mem",width:40,align:"right",renderer:Ext.util.Format.jpMoney=function(f){f=f/(1024*1024*1024);
n=f*100;
n=Math.round(n);
n=n/100;
return n+"G"},sortable:true}]);
a.defaultSortable=true;
var c=new Ext.data.JsonStore({url:"/machineinfolist",storeId:"hostname",fields:[{name:"hostname",type:"string"},{name:"ipaddr",type:"string"},{name:"macaddr",type:"string"},{name:"grabo",type:"string"},{name:"mem",type:"int"},{name:"cpu",type:"string"}]});
var b=new Ext.grid.GridPanel({region:"center",border:false,ds:c,cm:a,autoExpandColumn:"hostname",viewConfig:{forceFit:true},height:340,loadMask:{msg:"マシン構成リストデータ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(f){c.load()}});
var e=function(){G.amachine_dlg.hide();
G.amachine_dlg=null};
var d=new Ext.Window({title:"マシン構成リスト",animateTarget:"act-btn-mach",iconCls:"btn-macha",closeAction:"hide",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:400,width:850,modal:true,proxyDrag:true,shadow:true,items:[b],buttons:[{text:"閉じる",handler:function(){e()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){e()}}]});
b.on("rowdblclick",function(f,o,l){var k=f.getStore().getAt(o).get("hostname");
var p=f.getStore().getAt(o).get("ipaddr");
var q=f.getStore().getAt(o).get("macaddr");
var h=f.getStore().getAt(o).get("grabo");
var m=f.getStore().getAt(o).get("mem");
var i=f.getStore().getAt(o).get("cpu");
var g=Math.round(m/(1024*1024*1024)*100)/100;
var j="マシン名："+k+"<br>IPアドレス："+p+"<br>MACアドレス："+q+"<br>グラボ："+h+"<br>ＣＰＵ："+i+"<br>メモリ："+g+"GBytes ("+m+"Bytes)";
this.detail_info_dlg=new Ext.Window({id:"detail_info_dlg",title:"詳細",iconCls:"btn-macha",closeAction:"close",closable:false,shadow:true,draggable:true,resizable:false,fixedcenter:true,collapsible:false,shim:true,modal:true,width:400,height:150,layout:"fit",buttonAlign:"right",constrain:true,items:[{html:j}],buttons:[{text:"閉じる",handler:function(){this.detail_info_dlg.close()},scope:this}]});
this.detail_info_dlg.setTitle("詳細@"+k);
this.detail_info_dlg.show()});
b.switch_target();
d.grid=b;
G.amachine_dlg=d}else{G.amachine_dlg.hide()}return G.amachine_dlg}function build_network_dialog(b,c){if(!G.net_dlg){var e=new Ext.data.JsonStore({url:"/connectionlist",baseParams:{macaddr:c},storeId:"remote_addr",sortInfo:{field:"remote_port",direction:"ASC"},fields:[{name:"local_addr",type:"string"},{name:"local_port",type:"int"},{name:"remote_addr",type:"string"},{name:"remote_port",type:"int"},{name:"status",type:"string"}]});
var a=new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(),{id:"col-remote_addr",header:"接続先IP",dataIndex:"remote_addr",width:120,align:"right",sortable:true},{header:"接続元ポート",dataIndex:"local_port",width:60,align:"right",sortable:true},{header:"接続先ポート",dataIndex:"remote_port",width:60,align:"right",sortable:true}]);
a.defaultSortable=true;
var d=new Ext.grid.GridPanel({region:"center",border:false,ds:e,cm:a,autoExpandColumn:"pid",viewConfig:{forceFit:true},height:340,width:455,loadMask:{msg:"接続先データ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(h){e.load()}});
var g=function(){G.net_dlg.hide();
G.net_dlg=null};
var f=new Ext.Window({animateTarget:"act-btn-net",iconCls:"btn-proc",layout:"fit",border:false,plain:true,closeAction:"hide",closable:false,resizable:false,height:410,width:450,modal:true,proxyDrag:true,shadow:true,shadowOffset:10,constrain:true,items:[d],tbar:[{cls:"x-btn-text-icon",text:"更新",icon:ICON_PATH+"/ah.png",tooltip:"接続一覧を更新します",handler:function(){e.load()},scope:this}],buttons:[{text:"閉じる",handler:function(){g()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){g()}}]});
d.switch_target();
f.grid=d;
G.net_dlg=f}return G.net_dlg}function build_machine_dialog(b,c){if(!G.machine_dlg){var a=new Ext.grid.ColumnModel([{id:"col-name",header:"対象",dataIndex:"name",width:220,align:"right",sortable:true},{header:"値",dataIndex:"val",width:260,align:"left",sortable:true}]);
a.defaultSortable=true;
var e=new Ext.data.JsonStore({url:"/machineinfo",baseParams:{macaddr:c},storeId:"name",fields:[{name:"name",type:"string"},{name:"val",type:"string"}]});
var d=new Ext.grid.GridPanel({region:"center",border:false,ds:e,cm:a,autoExpandColumn:"hostname",viewConfig:{forceFit:true},height:340,loadMask:{msg:"マシン構成リストデータ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(h){e.load()}});
var g=function(){G.machine_dlg.hide();
G.machine_dlg=null};
var f=new Ext.Window({animateTarget:"act-btn-mach",closeAction:"hide",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:410,width:450,modal:true,proxyDrag:true,shadow:true,items:[d],buttons:[{text:"閉じる",handler:function(){g()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){g()}}]});
d.switch_target();
f.grid=d;
G.machine_dlg=f}return G.machine_dlg}function build_install_dialog(b,c){if(!G.install_dlg){var a=new Ext.grid.ColumnModel([{id:"col-val",header:"インストール",dataIndex:"val",width:220,align:"right",sortable:true},{header:"Version",dataIndex:"ver",width:60,align:"right",sortable:true,renderer:function(h){switch(h){case"":return"不明";
default:return h}}}]);
var e=new Ext.data.JsonStore({url:"/install",baseParams:{macaddr:c},storeId:"val",fields:[{name:"val",type:"string"},{name:"ver",type:"string"}]});
var d=new Ext.grid.GridPanel({region:"center",border:false,ds:e,cm:a,autoExpandColumn:"hostname",viewConfig:{forceFit:true},height:340,loadMask:{msg:"インストールリストデータ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(h){e.load()}});
d.on("rowdblclick",function(i,h,j){window.open("http://www.plustar.jp/proc.php?q="+i.getStore().getAt(h).get("val"),"google_search")});
var g=function(){G.install_dlg.hide();
G.install_dlg=null};
var f=new Ext.Window({animateTarget:"act-btn-inst",closeAction:"hide",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:410,width:450,modal:true,proxyDrag:true,shadow:true,items:[d],tbar:[{cls:"x-btn-text-icon",text:"更新",icon:ICON_PATH+"/ah.png",tooltip:"インストールモジュール一覧を更新します",handler:function(){e.load()},scope:this},"-",{cls:"x-btn-text-icon",text:"モジュール検索",icon:ICON_PATH+"/zm.png",tooltip:"インストールモジュールの検索を行います",handler:onInstallModSearch,scope:this}],buttons:[{text:"閉じる",handler:function(){g()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){g()}}]});
d.switch_target();
f.grid=d;
G.install_dlg=f}return G.install_dlg}function onInstallModSearch(){var b=G.install_dlg.grid.getSelectionModel().getSelected();
if(!b){Ext.MessageBox.show({title:"メッセージ",msg:"検索するインストールモジュールを選択してください。",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});
return}var a=b.get("val");
window.open("http://www.plustar.jp/proc.php?q="+a,"google_search")}function build_url_dialog(b,c){if(!G.url_dlg){var a=new Ext.grid.ColumnModel([{id:"col-title",header:"タイトル",dataIndex:"title",width:220,align:"right",sortable:true}]);
var e=new Ext.data.JsonStore({url:"/url",baseParams:{macaddr:c},storeId:"title",fields:[{name:"url",type:"string"},{name:"title",type:"string"}]});
var d=new Ext.grid.GridPanel({region:"center",border:false,ds:e,cm:a,autoExpandColumn:"hostname",viewConfig:{forceFit:true},height:340,loadMask:{msg:"ウェブ参照履歴データ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(h){e.load()}});
var g=function(){G.url_dlg.hide();
G.url_dlg=null};
var f=new Ext.Window({animateTarget:"act-btn-url",closeAction:"hide",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:410,width:450,modal:true,proxyDrag:true,shadow:true,items:[d],buttons:[{text:"閉じる",handler:function(){g()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){g()}}]});
d.switch_target();
f.grid=d;
G.url_dlg=f}return G.url_dlg}function build_wakeup_dialog(){if(!G.wakeup_dlg){var b=new Ext.data.JsonStore({url:"/stopmcheinelist",storeId:"hn",sortInfo:{field:"hn",direction:"ASC"},fields:[{name:"hn",type:"string"},{name:"mc",type:"string"}]});
b.load();
var d=new Ext.form.ComboBox({hiddenName:"macaddr",fieldLabel:"起動マシン",allowBlank:false,store:b,displayField:"hn",valueField:"mc",editable:false,typeAhead:true,mode:"local",forceSelection:true,triggerAction:"all",emptyText:"対象マシンを選択してください",selectOnFocus:true});
var a=new Ext.form.FormPanel({url:"/wakeup",method:"POST",trackResetOnLoad:true,timeout:10,standardSubmit:true,labelWidth:70,frame:true,bodyStyle:"padding:5px 5px 0",width:200,defaultType:"textfield",items:[d],buttons:[{text:"起動",handler:function(){var f=d.getValue();
if(f.length===0){Ext.MessageBox.show({title:"エラー",msg:"対象マシンを選択してください",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR});
d.focus();
return}else{Ext.Ajax.request({url:"/wakeup",params:{macaddr:f}});
Ext.MessageBox.show({title:"メッセージ",msg:'起動処理要求を送信しました<br>暫くすると起動します<br><br><a href="'+HELPPAGE_URL+'8" target="_blank">起動しない場合...</a>',width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});
e()}}},{text:"閉じる",handler:function(){e()}}]});
var e=function(){c.hide();
G.wakeup_dlg=null};
var c=new Ext.Window({animateTarget:"act-btn-wakeup",closeAction:"hide",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:123,width:400,modal:true,proxyDrag:true,shadow:true,items:[a],keys:[{key:Ext.EventObject.ESC,handler:function(){e()}}]});
G.wakeup_dlg=c}return G.wakeup_dlg}function build_updatehistory_dialog(){if(!G.updatehistory_dlg){var a=new Ext.grid.ColumnModel([{id:"col-dy",header:"リリース日",dataIndex:"dy",width:120,align:"right",sortable:true},{header:"更新内容",dataIndex:"fu",width:260,align:"left",sortable:true}]);
var c=new Ext.data.JsonStore({url:"/updatehistory",storeId:"dy",sortInfo:{field:"dy",direction:"DESC"},fields:[{name:"dy",type:"string"},{name:"fu",type:"string"}]});
var b=new Ext.grid.GridPanel({region:"center",border:false,ds:c,cm:a,autoExpandColumn:"dy",viewConfig:{forceFit:true},height:340,loadMask:{msg:"アップデート履歴データ取得中..."},autoScroll:true,layout:"fit",stripeRows:true,switch_target:function(f){c.load()}});
var e=function(){G.updatehistory_dlg.hide();
G.updatehistory_dlg=null};
var d=new Ext.Window({animateTarget:"act-btn-help",iconCls:"btn-his",closeAction:"hide",layout:"fit",border:false,plain:true,closable:false,resizable:false,height:410,width:450,modal:true,proxyDrag:true,shadow:true,items:[b],buttons:[{text:"閉じる",handler:function(){e()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){e()}}]});
b.switch_target();
d.grid=b;
G.updatehistory_dlg=d}return G.updatehistory_dlg}function build_wait_dialog(c){Ext.MessageBox.show({title:"しばらくお待ちください...",msg:c,progressText:"取得中...",width:300,progress:true,closable:false});
var b=function(d){return function(){if(d==12){Ext.MessageBox.hide()}else{var e=d/11;
Ext.MessageBox.updateProgress(e,Math.round(100*e)+"% 完了")}}};
for(var a=1;
a<13;
a++){setTimeout(b(a),a*500)}}var action={perform:function(a,e,f){var d=G.main_wnd.grid.getSelectionModel().getSelected();
if(!d){Ext.MessageBox.show({title:"注意",msg:a+'するPCを選択してください。<br><a href="'+HELPPAGE_URL+'5" target="_blank">詳細情報...</a>',width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.WARNING});
return}var c=d.id;
var b=d.data.hostname;
if(f){Ext.MessageBox.confirm("確認",String.format('マシン名 "{0}" のPCを{1}しようとしています。<br />よろしいですか?',b,a),function(g){if(g=="yes"){e(b,c)}})}else{e(b,c)}},wakeup:function(){var a=build_wakeup_dialog();
a.setTitle("マシンの起動");
a.show()},shutdown:function(){action.perform("シャットダウン",function(a,b){Ext.Ajax.request({url:"/shutdown",params:{macaddr:b}})},true)},reboot:function(){action.perform("再起動",function(a,b){Ext.Ajax.request({url:"/reboot",params:{macaddr:b}})},true)},process:function(){action.perform("プロセス一覧を取得",function(a,b){var d=build_process_dialog(a,b);
if(d!==null){d.setTitle("プロセス一覧@"+a);
d.show()}else{var c="プロセス情報取得中...";
build_wait_dialog(c)}})},psync:function(){action.perform("同期を実行する対象",function(a,b){Ext.MessageBox.show({title:"エラー",iconCls:"btn-sync",width:300,msg:'同期システムは未契約です。<br><a href="'+HELPPAGE_URL+'98" target="_blank">詳細情報...</a>',buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR})})},amachinelist:function(){var a=build_machine_list_dialog();
a.setTitle("マシン構成");
a.show()},option:function(){var a=build_option_dialog();
a.suppression_grid.switch_target();
a.buttons[2].disable();
a.show()},manual:function(){window.open(HELPPAGE_URL+"help")},log:function(){var a=build_log_dialog();
a.setTitle("クライアント通知ログ");
a.show()},license:function(){var a=build_license_dialog();
a.show()},analyzer:function(){window.open(HELPPAGE_URL+"ext")},net:function(){action.perform("接続先を取得する",function(a,b){var d=build_network_dialog(a,b);
if(d!==null){d.setTitle("接続先一覧@"+a);
d.show()}else{var c="接続先情報取得中...";
build_wait_dialog(c)}})},machinelist:function(){action.perform("マシン構成を取得する",function(a,b){var c=build_machine_dialog(a,b);
c.setTitle("マシン構成@"+a);
c.show()})},install:function(){action.perform("インストールアプリケーション情報を取得する",function(a,b){var c=build_install_dialog(a,b);
c.setTitle("インストールアプリケーション情報@"+a);
c.show()})},weburl:function(){action.perform("ウェブ参照履歴を取得する",function(a,b){var c=build_url_dialog(a,b);
c.setTitle("ウェブ参照履歴情報@"+a);
c.show()})},transcope:function(){action.perform("メンテナンス履歴を取得する",function(a,b){var c=build_transcope_dialog(a,b);
c.setTitle("メンテナンス履歴情報@"+a);
c.show()})},psbug:function(){var a=Ext.get("lic_cname").dom.innerHTML;
var b=Ext.get("lic_version").dom.innerHTML;
window.open(CONTACT_URL+"b&c="+a+"&s=&ver="+b,"バグ報告","status=yes,width=700,height=450")},psreq:function(){var a=Ext.get("lic_cname").dom.innerHTML;
var b=Ext.get("lic_version").dom.innerHTML;
window.open(CONTACT_URL+"r&c="+a+"&s=&ver="+b,"機能要望","status=yes,width=700,height=450")},psqus:function(){var a=Ext.get("lic_cname").dom.innerHTML;
var b=Ext.get("lic_version").dom.innerHTML;
window.open(CONTACT_URL+"q&c="+a+"&s=&ver="+b,"質問","status=yes,width=700,height=450")},updatehistory:function(){var a=build_updatehistory_dialog();
a.setTitle("アップデート履歴");
a.show()},screenshot:function(){action.perform("スクリーンショットを取得",function(b,c){var a=build_screenshot_password_prompt();
var d=b+"のスクリーンショット";
Ext.get("sshot_pwd").focus();
a.callback=function(e){var f=Ext.MessageBox.show({title:"しばらくお待ちください...",msg:d+"を取得しています...",progressText:"取得中...",width:300,progress:true,closable:false});
Ext.Ajax.request({url:"/screenshot",params:{macaddr:c,password:e},success:function(h,k){var o=build_screenshot_dialog(d);
o.show();
o.hide();
o.body.dom.innerHTML='<img id="sshot-img" />';
var g=Ext.get("sshot-img");
g.set({src:"/screenshot?_dc="+new Date().getTime(),alt:d}).on({click:{fn:handler.sshot_zoom,scope:g},load:{fn:handler.sshot_zoom,scope:g}});
var m=null;
var l=function(i){return function(){if(i==120){if(f.isVisible()){f.hide();
o.hide();
o=null;
Ext.MessageBox.show({title:"エラー",iconCls:"btn-sshot",msg:'スクリーンショットの取得に失敗しました。<br />電源が入っていないか、ログインしていない可能性があります。<br><a href="'+HELPPAGE_URL+'3" target="_blank">詳細情報...</a>',width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR})}}else{var p=i/119;
if(g.actualSize){clearTimeout(m);
m=null;
if(f!==null){f.hide()}f=null;
o.setTitle(d);
o.show()}else{if(f!==null){f.updateProgress(p,Math.round(100*p)+"% 処理中...")}}}}};
for(var j=1;
j<121;
j++){m=setTimeout(l(j),j*500)}},failure:function(){Ext.MessageBox.show({title:"エラー",iconCls:"btn-sshot",msg:"パスワードが不正です。",width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR})}})};
a.show();
setTimeout("Ext.get('sshot_pwd').focus()",1)})}};
var handler={sshot_zoom:function(){var a=G.sshot_dlg;
if(!this.actualSize){this.actualSize={width:this.getWidth(),height:this.getHeight()}}if(this.getWidth()==this.actualSize.width){a.body.setStyle("overflow","hidden");
this.set(a.body.getViewSize());
this.set({title:"クリックで拡大"})}else{a.body.setStyle("overflow","auto");
this.set(this.actualSize);
this.set({title:"クリックで縮小"})}if(!a.isVisible()){a.show()}},item_check:function(b,a){if(a){if(b.value){thread.restart(b.value)}else{thread.stop()}}},load_main_grid:function(b){var a=b.getTotalCount();
var d=b.getCount();
Ext.getDom("boot_pc_count").innerHTML=d;
Ext.getDom("boot_pc_total").innerHTML=a;
Ext.getDom("boot_pc_ratio").innerHTML=Math.round(a>0?d*100/a:0);
Ext.getDom("proc_count").innerHTML=G.main_wnd.proc_count;
Ext.getDom("conn_count").innerHTML=G.main_wnd.conn_count;
G.main_wnd.proc_count=0;
G.main_wnd.conn_count=0},open_window:function(b,a){window.open(a.href)}};
function build_screenshot_dialog(b){if(!G.sshot_dlg){var a=new Ext.Window({id:"sshot-dlg",animateTarget:"act-btn-sshot",iconCls:"btn-sshot",autoScroll:true,autoCreate:true,closeAction:"hide",closable:false,resizable:false,height:600,width:800,modal:true,proxyDrag:true,shadow:true,shadowOffset:10,buttons:[{text:"閉じる",handler:function(){c()}}],keys:[{key:Ext.EventObject.ESC,handler:function(){c()}}]});
var c=function(){Ext.get("sshot-img").actualSize=null;
a.hide()};
G.sshot_dlg=a}return G.sshot_dlg}var filter={img_tag:'<div title="{1}" class="sri-{0}" /></div>',proc:function(a){G.main_wnd.proc_count+=a;
return a},conn:function(a){G.main_wnd.conn_count+=a;
return a},meter:function(a){return String.format(filter.img_tag,Math.round(a/10),a+"%")}};
var thread={proc:function(){G.main_wnd.grid.getStore().load()},start:function(a){if(!this.timer_id){this.proc();
this.timer_id=setInterval(this.proc,a*1000)}},stop:function(){if(this.timer_id){clearInterval(this.timer_id);
this.timer_id=null}},restart:function(a){this.stop();
this.start(a)}};
Ext.onReady(function(){var f=Ext.getDom("_firebugConsole");
if(f!==null){f.innerHTML="FireBugを無効にしてからお使いください。";
Ext.MessageBox.show({title:"メッセージ",msg:'FireBugを無効にしてからお使いください。<br><a href="'+HELPPAGE_URL+'7" target="_blank">エラー詳細情報...</a>',width:300,buttons:Ext.MessageBox.OK,icon:Ext.MessageBox.WARNING});
return}function c(g){Ext.get(g).on({click:{stopEvent:true,delegate:"a",fn:function(i,h){window.open(h.href)}}})}c("powered");
c("copyright");
var b=new Ext.Viewport({layout:"border",window:{layout:"fit"},items:[{region:"north",el:"header",xtype:"box",height:55,border:false},{region:"center",layout:"fit",id:"content",xtype:"box",margins:"0 1 0 0",listeners:{resize:function(i,j,g,k,h){if(d){d.setSize(j,g)}}}},{region:"south",el:"footer",xtype:"box",height:16,border:false}]});
var e=new Ext.data.JsonStore({url:"/machinelist",root:"results",totalProperty:"total",storeId:"hostname",id:"macaddr",fields:[{name:"user_job",type:"int"},{name:"hostname",type:"string"},{name:"ipaddr",type:"string"},{name:"boot_time",type:"date"},{name:"time_span",type:"string"},{name:"proc",type:"int"},{name:"connections",type:"int"},{name:"mem",type:"int"},{name:"disk",type:"int"},{name:"cpu",type:"int"},{name:"traffic",type:"int"},{name:"net_in",type:"int"},{name:"net_out",type:"int"}]});
e.on("load",handler.load_main_grid);
e.on("load",function(g,h,j){var k=g.getCount();
if(k<1){var i="ネットワーク構成情報取得中...";
build_wait_dialog(i)}});
var a=new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(),{header:"利用",dataIndex:"user_job",width:41,tooltip:"各端末の利用状況<br>&nbsp;
<img src="+ICON_PATH+"/tr.png />：管理端末<br>&nbsp;
<img src="+ICON_PATH+"/se.png />：端末使用中<br>&nbsp;
<img src="+ICON_PATH+"/sg.png />：オンラインゲーム<br>&nbsp;
<img src="+ICON_PATH+"/ss.png />：ストリーミング<br>&nbsp;
<img src="+ICON_PATH+"/stv.png />：動画再生<br>&nbsp;
<img src="+ICON_PATH+"/sd.png />：ダウンロード<br>&nbsp;
<img src="+ICON_PATH+"/su.png />：アップロード<br>&nbsp;
<img src="+ICON_PATH+"/sw.png />：ネットサーフィン<br>&nbsp;
<img src="+ICON_PATH+"/son.png />：起動<br>",sortable:true,align:"center",renderer:function(g){switch(g){case 0:return'<img src="'+ICON_PATH+'/son.png" alt="起動" title="起動" />';
case 1:return'<img src="'+ICON_PATH+'/tr.png" alt="管理" title="管理" />';
case 2:return'<img src="'+ICON_PATH+'/ss.png" alt="ストリーミング" title="ストリーミング" />';
case 3:return'<img src="'+ICON_PATH+'/stv.png" alt="動画" title="動画" />';
case 4:return'<img src="'+ICON_PATH+'/sd.png" alt="ダウンロード" title="ダウンロード" />';
case 5:return'<img src="'+ICON_PATH+'/su.png" alt="アップロード" title="アップロード" />';
case 6:return'<img src="'+ICON_PATH+'/sg.png" alt="ゲーム" title="ゲーム" />';
case 7:return'<img src="'+ICON_PATH+'/sw.png" alt="WEB" title="WEB" />';
case 8:return'<img src="'+ICON_PATH+'/se.png" alt="使用中" title="使用中" />';
default:return'<img src="'+ICON_PATH+'/son.png" alt="起動" title="起動" />'}}},{id:"col-hostname",header:"マシン名",dataIndex:"hostname",width:140,tooltip:"マシン名",sortable:true},{header:"IP",dataIndex:"ipaddr",width:90,tooltip:"IPアドレス",sortable:true},{header:"起動時間",dataIndex:"boot_time",width:110,tooltip:"起動した時間",renderer:Ext.util.Format.dateRenderer("Y/m/d H:i:s"),sortable:true},{header:"経過時間",dataIndex:"time_span",width:60,tooltip:"経過した時間",align:"right",sortable:true},{header:"プロセス",dataIndex:"proc",width:60,tooltip:"起動プロセス数",align:"right",renderer:filter.proc,sortable:true},{header:"接続数",dataIndex:"connections",width:60,tooltip:"外部接続数",align:"right",renderer:filter.conn,sortable:true},{header:"メモリ",dataIndex:"mem",width:68,tooltip:"メモリ使用率",align:"center",renderer:filter.meter,sortable:true},{header:"ディスク",dataIndex:"disk",width:68,tooltip:"ディスク使用率",align:"center",renderer:filter.meter,sortable:true},{header:"CPU",dataIndex:"cpu",width:68,tooltip:"CPU使用率",align:"center",renderer:filter.meter,sortable:true},{header:"通信量",dataIndex:"traffic",width:68,tooltip:"全体通信量に対する端末の使用量(%)",align:"center",renderer:filter.meter,sortable:true},{header:"受信",dataIndex:"net_in",width:68,tooltip:"対象端末の受信量(%)",align:"center",renderer:filter.meter,sortable:true},{header:"送信",dataIndex:"net_out",tooltip:"対象端末の送信量(%)",width:68,align:"center",renderer:filter.meter,sortable:true}]);
a.defaultSortable=false;
var d=new Ext.grid.GridPanel({renderTo:"grid",border:true,ds:e,cm:a,sm:new Ext.grid.RowSelectionModel({singleSelect:true}),autoExpandColumn:"col-hostname",viewConfig:{forceFit:true},autoWidth:true,stripeRows:true,autoScroll:true,tbar:[{id:"act-btn-procs",cls:"x-btn-text-icon",text:"",iconCls:"btn-proc",tooltip:"選択したPCのプロセス一覧を取得します",handler:action.process,scope:this},{id:"act-btn-net",cls:"x-btn-text-icon",text:"",iconCls:"btn-net",tooltip:"選択したPCの接続先一覧を表示します",handler:action.net,scope:this},{id:"act-btn-mach",cls:"x-btn-text-icon",text:"",iconCls:"btn-mach",tooltip:"選択したPCのマシン構成を表示します",handler:action.machinelist,scope:this},{id:"act-btn-inst",cls:"x-btn-text-icon",text:"",iconCls:"btn-inst",tooltip:"選択したPCのインストールリストを表示します",handler:action.install,scope:this},"-",{id:"act-btn-sync",cls:"x-btn-text-icon",text:"",iconCls:"btn-sync",tooltip:"選択したPCのマシン間の同期を行います",handler:action.psync,scope:this},{id:"act-btn-sshot",cls:"x-btn-text-icon",text:"",iconCls:"btn-sshot",tooltip:"選択したPCのスクリーンショットを取得します",handler:action.screenshot,scope:this},"-",{id:"act-btn-wakeup",cls:"x-btn-text-icon",text:"",icon:ICON_PATH+"/ac.png",tooltip:"選択したPCを起動します",handler:action.wakeup,scope:this},{id:"act-btn-shotdown",cls:"x-btn-text-icon",text:"",icon:ICON_PATH+"/ca.png",tooltip:"選択したPCをシャットダウンします",handler:action.shutdown,scope:this},{id:"act-btn-reboot",cls:"x-btn-text-icon",text:"",icon:ICON_PATH+"/ar.png",tooltip:"選択したPCを再起動します",handler:action.reboot,scope:this},"-",{id:"act-btn-analyzer",cls:"x-btn-text-icon",text:"",icon:ICON_PATH+"/ae.png",tooltip:"稼動プロセスアナライザー",handler:action.analyzer},"-",{id:"act-btn-tools",icon:ICON_PATH+"/wh.png",tooltip:"各種設定およびログの確認ができます",cls:"x-btn-text-icon",text:"",menu:{items:[{icon:ICON_PATH+"/cl.png",cls:"x-btn-text-icon",text:"更新間隔",menu:{items:[{id:"interval-10",text:"10秒",value:10,checked:false,group:"interval",checkHandler:handler.item_check},{id:"interval-20",text:"20秒",value:20,checked:false,group:"interval",checkHandler:handler.item_check},{id:"interval-30",text:"30秒",value:30,checked:false,group:"interval",checkHandler:handler.item_check},{id:"interval-60",text:"60秒",value:60,checked:false,group:"interval",checkHandler:handler.item_check},{id:"interval-120",text:"120秒",value:120,checked:false,group:"interval",checkHandler:handler.item_check},{id:"interval-0",text:"無効",value:0,checked:false,group:"interval",checkHandler:handler.item_check}]}},{text:"クライアント通知ログ...",iconCls:"btn-log",handler:action.log},{text:"マシン構成リスト...",icon:ICON_PATH+"/ml.png",handler:action.amachinelist},{text:"オプション...",iconCls:"btn-opt",handler:action.option}]}},{id:"act-btn-help",icon:ICON_PATH+"/hp.png",cls:"x-btn-text-icon",text:"",menu:{items:[{text:"オンラインマニュアル",icon:ICON_PATH+"/bk.png",handler:action.manual},"-",{text:"バグ報告...",iconCls:"btn-bug",handler:action.psbug},{text:"機能要望...",iconCls:"btn-req",handler:action.psreq},{text:"質問...",iconCls:"btn-qes",handler:action.psqus},"-",{text:"アップデート履歴",iconCls:"btn-his",handler:action.updatehistory},"-",{text:"ライセンス",iconCls:"btn-key",handler:action.license}]}}],bbar:new Ext.Toolbar({items:['PC合計: <span id="boot_pc_total">0</span>台',"-",'起動PC: <span id="boot_pc_count">0</span>台',"-",'起動PC率: <span id="boot_pc_ratio">0</span>%',"-",'プロセス合計: <span id="proc_count">0</span>',"-",'接続数合計: <span id="conn_count">0</span>',"->"]})});
d.setHeight(Ext.getBody().dom.clientHeight-64);
d.on("rowcontextmenu",function(h,g,j){var i=h.getSelectionModel().getSelections();
if(!this.clickharukomenu){this.clickharukomenu=new Ext.menu.Menu({id:"harumenu",items:[{text:"プロセス",iconCls:"btn-proc",handler:action.process,scope:this},{text:"接続先",iconCls:"btn-net",handler:action.net,scope:this},{text:"マシン構成",iconCls:"btn-mach",handler:action.machinelist,scope:this},{text:"インストールリスト",iconCls:"btn-inst",handler:action.install,scope:this},"-",{cls:"x-btn-text-icon",text:"同期",iconCls:"btn-sync",handler:action.psync,scope:this},{text:"スクリーンショット",iconCls:"btn-sshot",handler:action.screenshot,scope:this},"-",{text:"シャットダウン",icon:ICON_PATH+"/ca.png",handler:action.shutdown,scope:this},{text:"再起動",icon:ICON_PATH+"/ar.png",handler:action.reboot,scope:this}]})}j.stopEvent();
if(this.ctxRow){Ext.fly(this.ctxRow).removeClass("x-node-ctx");
this.ctxRow=null}this.ctxRow=this.view.getRow(g);
this.ctxRecord=this.store.getAt(g);
Ext.fly(this.ctxRow).addClass("x-node-ctx");
this.clickharukomenu.showAt(j.getXY())});
G.main_wnd.grid=d;
Ext.getCmp("interval-"+DEFAULT_INTERVAL).setChecked(true)});

